#pragma once
#include <bgame/bg_public.h>
#include <clientscript/cscr_variable.h>
#include <bgame/bg_local.h>
#include <game/actor.h>

struct WeaponComponentList;

void __cdecl PlayerCmd_setBlockWeaponPickup(scr_entref_t entref);
int __cdecl BG_PlayerWeaponSetBlockPickupWeapon(playerState_s *ps, unsigned int weaponIndex, bool blockPickupWeapon);
void __cdecl PlayerCmd_giveWeapon(scr_entref_t entref);
void __cdecl G_InitializeAmmo(gentity_s *pSelf, unsigned int weaponIndex, unsigned __int8 weaponModel, int hadWeapon);
int __cdecl G_GetNeededStartAmmo(gentity_s *pSelf, unsigned int weaponIndex);
int __cdecl BG_GetStartAmmo(unsigned int weaponIndex);
void __cdecl PlayerCmd_giveNextBaseWeaponDEVONLY(scr_entref_t entref);
void __cdecl WeaponComponentListAddAllPoints(WeaponComponentList *componentList);
void __cdecl WeaponComponentListToName(const WeaponComponentList *componentList, char *name, int size);
void __cdecl PlayerCmd_giveWeaponNextAttachmentDEVONLY(scr_entref_t entref);
void __cdecl PlayerCmd_calcWeaponOptions(scr_entref_t entref);
unsigned int __cdecl PlayerCmd_GetStatFromPlayer(unsigned int clientNum, const char **operands, int nOperands);
void __cdecl PlayerCmd_calcPlayerOptions(scr_entref_t entref);
void __cdecl PlayerCmd_setPlayerRenderOptions(scr_entref_t entref);
void __cdecl PlayerCmd_NextPlayerRenderOption(scr_entref_t entref);
void __cdecl PlayerCmd_SetHighlighted(scr_entref_t entref);
void __cdecl PlayerCmd_IsThrowingGrenade(scr_entref_t entref);
// LWSS ADD
void PlayerCmd_IsFiring(scr_entref_t entref);
void PlayerCmd_IsInMoveMode(scr_entref_t entref);
void PlayerCmd_IsMeleeing(scr_entref_t entref);
void PlayerCmd_IsSwitchingWeapons(scr_entref_t entref);
// LWSS END
void __cdecl PlayerCmd_takeWeapon(scr_entref_t entref);
void __cdecl PlayerCmd_takeAllWeapons(scr_entref_t entref);
void __cdecl PlayerCmd_getCurrentWeapon(scr_entref_t entref);
void __cdecl PlayerCmd_getCurrentWeaponClipAmmo(scr_entref_t entref);
bool __cdecl ClientPlaying(gentity_s *pSelf);
void __cdecl PlayerCmd_getCurrentOffhand(scr_entref_t entref);
void __cdecl PlayerCmd_setOffhandSecondaryClass(scr_entref_t entref);
void __cdecl PlayerCmd_setOffhandPrimaryClass(scr_entref_t entref);
void __cdecl PlayerCmd_getOffhandSecondaryClass(scr_entref_t entref);
void __cdecl PlayerCmd_hasWeapon(scr_entref_t entref);
void __cdecl PlayerCmd_switchToWeapon(scr_entref_t entref);
void __cdecl PlayerCmd_switchToOffhand(scr_entref_t entref);
void __cdecl PlayerCmd_getLockOnRadius(scr_entref_t entref);
void __cdecl PlayerCmd_getLockOnSpeed(scr_entref_t entref);
void __cdecl PlayerCmd_giveStartAmmo(scr_entref_t entref);
void __cdecl PlayerCmd_giveMaxAmmo(scr_entref_t entref);
void __cdecl PlayerCmd_getFractionStartAmmo(scr_entref_t entref);
void __cdecl PlayerCmd_getFractionMaxAmmo(scr_entref_t entref);
void __cdecl PlayerCmd_setOrigin(scr_entref_t entref);
void __cdecl PlayerCmd_SetVelocity(scr_entref_t entref);
void __cdecl PlayerCmd_setAngles(scr_entref_t entref);
void __cdecl PlayerCmd_getAngles(scr_entref_t entref);
void __cdecl PlayerCmd_CameraActivate(scr_entref_t entref);
void __cdecl PlayerCmd_CameraSetPosition(scr_entref_t entref);
void __cdecl PlayerCmd_CameraSetLookAt(scr_entref_t entref);
void __cdecl PlayerCmd_Revive(scr_entref_t entref);
void __cdecl PlayerCmd_RevivePlayer(scr_entref_t entref);
void __cdecl PlayerCmd_StartRevive(scr_entref_t entref);
void __cdecl PlayerCmd_StopRevive(scr_entref_t entref);
void __cdecl PlayerCmd_useButtonPressed(scr_entref_t entref);
void __cdecl PlayerCmd_ChangeSeatButtonPressed(scr_entref_t entref);
void __cdecl PlayerCmd_attackButtonPressed(scr_entref_t entref);
void __cdecl PlayerCmd_actionSlotOneButtonPressed(scr_entref_t entref);
void __cdecl PlayerCmd_actionSlotTwoButtonPressed(scr_entref_t entref);
void __cdecl PlayerCmd_actionSlotThreeButtonPressed(scr_entref_t entref);
void __cdecl PlayerCmd_actionSlotFourButtonPressed(scr_entref_t entref);
void __cdecl PlayerCmd_adsButtonPressed(scr_entref_t entref);
void __cdecl PlayerCmd_throwButtonPressed(scr_entref_t entref);
void __cdecl PlayerCmd_meleeButtonPressed(scr_entref_t entref);
void __cdecl PlayerCmd_jumpButtonPressed(scr_entref_t entref);
void __cdecl PlayerCmd_fragButtonPressed(scr_entref_t entref);
void __cdecl PlayerCmd_secondaryOffhandButtonPressed(scr_entref_t entref);
void __cdecl PlayerCmd_buttonPressedDEVONLY(scr_entref_t entref);
void __cdecl PlayerCmd_playerADS(scr_entref_t entref);
void __cdecl PlayerCmd_pingPlayer(scr_entref_t entref);
void __cdecl PlayerCmd_SetViewmodel(scr_entref_t entref);
void __cdecl PlayerCmd_GetViewmodel(scr_entref_t entref);
void __cdecl PlayerCmd_ShowViewmodel(scr_entref_t entref);
void __cdecl PlayerCmd_HideViewmodel(scr_entref_t entref);
void __cdecl PlayerCmd_setSpawnWeapon(scr_entref_t entref);
void __cdecl PlayerCmd_dropItem(scr_entref_t entref);
void __cdecl PlayerCmd_dropScavengerItem(scr_entref_t entref);
void __cdecl PlayerCmd_hasAGrenadePulledBack(scr_entref_t entref);
void __cdecl PlayerCmd_BotSetScriptGoal(scr_entref_t entref);
void __cdecl PlayerCmd_BotClearScriptGoal(scr_entref_t entref);
void __cdecl PlayerCmd_BotSetScriptEnemy(scr_entref_t entref);
void __cdecl PlayerCmd_BotClearScriptEnemy(scr_entref_t entref);
void __cdecl PlayerCmd_BotSetAttacker(scr_entref_t entref);
void __cdecl PlayerCmd_BotPressUseButton(scr_entref_t entref);
void __cdecl PlayerCmd_finishPlayerDamage(scr_entref_t entref);
bool __cdecl IsBulletImpactMOD(meansOfDeath_t mod);
void __cdecl ForceGrenadeThrow(playerState_s *ps);
void __cdecl ApplyKnockBack(gentity_s *pSelf, int damage, float *localdir, char dflags, bool allow_in_air);
void __cdecl PlayerCmd_Suicide(scr_entref_t entref);
// LWSS ADD
void PlayerCmd_BotPressAttackButton(scr_entref_t entref);
void PlayerCmd_GetLookaheadDist(scr_entref_t entref);
void PlayerCmd_GetLookaheadDir(scr_entref_t entref);
void PlayerCmd_GetThreat(scr_entref_t entref);
void PlayerCmd_HasScriptGoal(scr_entref_t entref);
// LWSS END
void __cdecl PlayerCmd_IsSplitscreen(scr_entref_t entref);
void __cdecl PlayerCmd_IsPlayerOnSameMachine(scr_entref_t entref);
void __cdecl PlayerCmd_InitDec20Terminal(scr_entref_t entref);
void __cdecl PlayerCmd_AttachToDec20Terminal(scr_entref_t entref);
void __cdecl PlayerCmd_DetachDec20Terminal(scr_entref_t entref);
void __cdecl PlayerCmd_IsInVehicle(scr_entref_t entref);
void __cdecl PlayerCmd_IsRemoteControlling(scr_entref_t entref);
void __cdecl PlayerCmd_GetVehicleOccupied(scr_entref_t entref);
void __cdecl PlayerCmd_OpenMenu(scr_entref_t entref);
void __cdecl PlayerCmd_OpenMenuNoMouse(scr_entref_t entref);
void __cdecl PlayerCmd_CloseMenu(scr_entref_t entref);
void __cdecl PlayerCmd_CloseInGameMenu(scr_entref_t entref);
void __cdecl PlayerCmd_SetWeaponAmmoClip(scr_entref_t entref);
void __cdecl SetWeaponAmmoClipDualWield(playerState_s *ps);
void __cdecl PlayerCmd_SetWeaponAmmoStock(scr_entref_t entref);
void __cdecl PlayerCmd_SetCurrentSpectatorClient(scr_entref_t entref);
void __cdecl PlayerCmd_GetWeaponAmmoClip(scr_entref_t entref);
void __cdecl PlayerCmd_GetWeaponAmmoStock(scr_entref_t entref);
void __cdecl PlayerCmd_AnyAmmoForWeaponModes(scr_entref_t entref);
void __cdecl iclientprintln(scr_entref_t entref);
void __cdecl iclientprintlnbold(scr_entref_t entref);
void __cdecl PlayerCmd_spawn(scr_entref_t entref);
void __cdecl PlayerCmd_setEnterTime(scr_entref_t entref);
void __cdecl BodyEnd(gentity_s *ent);
void __cdecl PlayerCmd_ClonePlayer(scr_entref_t entref);
void __cdecl PlayerCmd_SetClientDvar(scr_entref_t entref);
void __cdecl PlayerCmd_SetClientUIVisibilityFlag(scr_entref_t entref);
void __cdecl PlayerCmd_SetClientDvars(scr_entref_t entref);
void __cdecl PlayerCmd_PlayClientAirstrike(scr_entref_t entref);
void __cdecl PlayerCmd_PlayClientNapalm(scr_entref_t entref);
void __cdecl PlayerCmd_IsTalking(scr_entref_t entref);
void __cdecl PlayerCmd_FreezeControls(scr_entref_t entref);
void __cdecl PlayerCmd_FreezeControlsAllowLook(scr_entref_t entref);
void __cdecl PlayerCmd_AreControlsFrozen(scr_entref_t entref);
void __cdecl PlayerCmd_DisableUsability(scr_entref_t entref);
void __cdecl PlayerCmd_EnableUsability(scr_entref_t entref);
void __cdecl PlayerCmd_DisableWeapons(scr_entref_t entref);
void __cdecl PlayerCmd_EnableWeapons(scr_entref_t entref);
void __cdecl PlayerCmd_DisableDeathStreak(scr_entref_t entref);
void __cdecl PlayerCmd_EnableDeathStreak(scr_entref_t entref);
void __cdecl PlayerCmd_DeathStreakActive(scr_entref_t entref);
void __cdecl PlayerCmd_DisableOffhandWeapons(scr_entref_t entref);
void __cdecl PlayerCmd_EnableOffhandWeapons(scr_entref_t entref);
void __cdecl PlayerCmd_DisableWeaponCycling(scr_entref_t entref);
void __cdecl PlayerCmd_EnableWeaponCycling(scr_entref_t entref);
void __cdecl ScrCmd_PlayLocalSound(scr_entref_t entref);
void __cdecl ScrCmd_StopLocalSound(scr_entref_t entref);
void __cdecl PlayerCmd_SayAll(scr_entref_t entref);
void __cdecl PlayerCmd_SayTeam(scr_entref_t entref);
void __cdecl PlayerCmd_AllowADS(scr_entref_t entref);
void __cdecl PlayerCmd_AllowJump(scr_entref_t entref);
void __cdecl PlayerCmd_AllowSprint(scr_entref_t entref);
void __cdecl PlayerCmd_AllowStand(scr_entref_t entref);
void __cdecl PlayerCmd_AllowCrouch(scr_entref_t entref);
void __cdecl PlayerCmd_AllowProne(scr_entref_t entref);
void __cdecl PlayerCmd_AllowMelee(scr_entref_t entref);
void __cdecl PlayerCmd_SetSprintDuration(scr_entref_t entref);
void __cdecl PlayerCmd_SetSprintCooldown(scr_entref_t entref);
void __cdecl PlayerCmd_SetSpreadOverride(scr_entref_t entref);
void __cdecl PlayerCmd_ResetSpreadOverride(scr_entref_t entref);
void __cdecl PlayerCmd_AllowSpectateTeam(scr_entref_t entref);
void __cdecl PlayerCmd_GetGuid(scr_entref_t entref);
void __cdecl PlayerCmd_GetXuid(scr_entref_t entref);
void __cdecl PlayerCmd_IsHost(scr_entref_t entref);
void __cdecl PlayerCmd_IsLocalToHost(scr_entref_t entref);
void __cdecl PlayerCmd_BeginLocationSelection(scr_entref_t entref);
void __cdecl PlayerCmd_BeginLocationTypeSelection(scr_entref_t entref, locSel_t selectionType);
void __cdecl PlayerCmd_BeginLocationAirstrikeSelection(scr_entref_t entref);
void __cdecl PlayerCmd_BeginLocationMortarSelection(scr_entref_t entref);
void __cdecl PlayerCmd_BeginLocationArtillerySelection(scr_entref_t entref);
void __cdecl PlayerCmd_BeginLocationComlinkSelection(scr_entref_t entref);
void __cdecl PlayerCmd_BeginLocationNapalmSelection(scr_entref_t entref);
void __cdecl PlayerCmd_EndLocationSelection(scr_entref_t entref);
void __cdecl PlayerCmd_SetActionSlot(scr_entref_t entref);
void __cdecl PlayerCmd_GetWeaponsList(scr_entref_t entref);
void __cdecl PlayerCmd_GetWeaponsListPrimaries(scr_entref_t entref);
void __cdecl PlayerCmd_SetPerk(scr_entref_t entref);
void __cdecl BG_SetPerk(unsigned int *perks, unsigned int perkIndex);
void __cdecl PlayerCmd_HasPerk(scr_entref_t entref);
void __cdecl PlayerCmd_GetPerks(scr_entref_t entref);
void __cdecl PlayerCmd_UnsetPerk(scr_entref_t entref);
void __cdecl BG_UnsetPerk(unsigned int *perks, unsigned int perkIndex);
void __cdecl PlayerCmd_ClearPerks(scr_entref_t entref);
void __cdecl BG_ClearPerks(unsigned int *perks);
void __cdecl PlayerCmd_EnableInvulnerability(scr_entref_t entref);
void __cdecl PlayerCmd_DisableInvulnerability(scr_entref_t entref);
void __cdecl PlayerCmd_SetRank(scr_entref_t entref);
void __cdecl PlayerCmd_SetLastStandPrevWeap(scr_entref_t entref);
void __cdecl PlayerCmd_ClientSysSetState(scr_entref_t entref);
void __cdecl PlayerCmd_WeaponLockStart(scr_entref_t entref);
void __cdecl PlayerCmd_WeaponLockFinalize(scr_entref_t entref);
void __cdecl PlayerCmd_WeaponLockFree(scr_entref_t entref);
void __cdecl PlayerCmd_WeaponLockTargetTooClose(scr_entref_t entref);
void __cdecl PlayerCmd_WeaponLockNoClearance(scr_entref_t entref);
void __cdecl PlayerCmd_ReLinkToTurret(scr_entref_t entref);
void __cdecl PlayerCmd_CarryTurret(scr_entref_t entref);
void __cdecl PlayerCmd_StopCarryTurret(scr_entref_t entref);
void __cdecl PlayerCmd_LinkGuidedMissileCamera(scr_entref_t entref);
void __cdecl PlayerCmd_UnlinkGuidedMissileCamera(scr_entref_t entref);
void __cdecl PlayerCmd_isCarryingTurret(scr_entref_t entref);
void __cdecl PlayerCmd_CanPlayerPlaceTurret(scr_entref_t entref);
void PlayerCmd_SetTurrentHint(scr_entref_t entref); // LWSS ADD
void __cdecl PlayerCmd_AllowLean(scr_entref_t entref);
void __cdecl PlayerCmd_EnableHealthShield(scr_entref_t entref);
void __cdecl PlayerCmd_UploadScore(scr_entref_t entref);
void __cdecl PlayerCmd_ThrowDownWeapon(scr_entref_t entref);
void __cdecl PlayerCmd_IsLookingAt(scr_entref_t entref);
void __cdecl PlayerCmd_updateWeaponOptions(scr_entref_t entref);
void __cdecl PlayerCmd_isWeaponOverheating(scr_entref_t entref);
void __cdecl PlayerCmd_SetAdsWidthAndLerp(scr_entref_t entref);
void __cdecl PlayerCmd_ResetAdsWidthAndLerp(scr_entref_t entref);
void __cdecl PlayerCmd_startCameraTween(scr_entref_t entref);
void __cdecl PlayerCmd_setViewLockEnt(scr_entref_t entref);
void __cdecl PlayerCmd_SetPlayerViewRateScale(scr_entref_t entref);
void __cdecl PlayerCmd_ResetPlayerViewRateScale(scr_entref_t entref);
void __cdecl PlayerCmd_clearViewLockEnt(scr_entref_t entref);
void __cdecl PlayerCmd_getCameraPos(scr_entref_t entref);
void __cdecl PlayerCmd_GetVelocity(scr_entref_t entref);
void __cdecl PlayerCmd_reverseButtonPressed(scr_entref_t entref);
void __cdecl PlayerCmd_getViewHeight(scr_entref_t entref);
void __cdecl PlayerCmd_getNormalizedMovement(scr_entref_t entref);
void __cdecl PlayerCmd_getNormalizedCameraMovement(scr_entref_t entref);
void __cdecl PlayerCmd_useButtonHeld(scr_entref_t entref);
void __cdecl PlayerCmd_sprintButtonPressed(scr_entref_t entref);
void __cdecl PlayerCmd_gasButtonPressed(scr_entref_t entref);
void __cdecl PlayerCmd_reloadButtonPressed(scr_entref_t entref);
void __cdecl PlayerCmd_CheckButtonPressed(scr_entref_t entref);
void __cdecl PlayerCmd_notifyOnCommand(scr_entref_t entref);
void __cdecl PlayerCmd_OpenMainMenu(scr_entref_t entref);
void __cdecl PlayerCmd_PlayerKnockback(scr_entref_t entref);
void __cdecl PlayerCmd_CloseMainMenu(scr_entref_t entref);
void __cdecl ScrCmd_SetAutoPickup(scr_entref_t entref);
void __cdecl PlayerCmd_GetWeaponRenderOptions(scr_entref_t entref);
void __cdecl PlayerCmd_DisableWeaponFire(scr_entref_t entref);
void __cdecl PlayerCmd_EnableWeaponReload(scr_entref_t entref);
void __cdecl PlayerCmd_DisableWeaponReload(scr_entref_t entref);
void __cdecl PlayerCmd_EnableWeaponFire(scr_entref_t entref);
void __cdecl PlayerCmd_NightVisionForceOff(scr_entref_t entref);
void __cdecl PlayerCmd_ForceViewmodelAnimation(scr_entref_t entref);
void __cdecl PlayerCmd_DisableTurretDismount(scr_entref_t entref);
void __cdecl PlayerCmd_EnableTurretDismount(scr_entref_t entref);
void __cdecl PlayerCmd_UploadTime(scr_entref_t entref);
void __cdecl PlayerCmd_ClearDamageIndicator(scr_entref_t entref);
void __cdecl PlayerCmd_UndoLastStand(scr_entref_t entref);
void __cdecl PlayerCmd_GetCurrentArcadeHighScore(scr_entref_t entref);
void __cdecl PlayerCmd_GetScoreMultiplier(scr_entref_t entref);
void __cdecl PlayerCmd_SetScoreMultiplier(scr_entref_t entref);
void __cdecl PlayerCmd_SetLowReady(scr_entref_t entref);
void __cdecl PlayerCmd_SetLoweredWeapon(scr_entref_t entref);
void __cdecl PlayerCmd_SetScriptHintString(scr_entref_t entref);
void __cdecl PlayerCmd_AllowPickupWeapons(scr_entref_t entref);
void (__cdecl *__cdecl Player_GetMethod(const char **pName))(scr_entref_t);
