#pragma once

void __cdecl VP_ResetLinks();
__int16 __cdecl VP_GetNextFreePathNode();
void __cdecl VP_ClearNode(vehicle_node_t *node);
__int16 __cdecl VP_GetNodeIndex(unsigned __int16 name, float *origin);
__int16 __cdecl VP_FindClosestPathNode(const float *pos);
vehicle_custom_path_t *__cdecl VP_GetFreeCustomPath();
void __cdecl VP_FreeCustomPath(vehicle_custom_path_t *path);
int __cdecl VP_FindPath(float *start, float *end, vehicle_pathpos_t *vpp);
void __cdecl VP_DrawCustomPath(vehicle_custom_path_t *customPath);
void __cdecl VP_DrawPath(const vehicle_pathpos_t *vpp);
void __cdecl VP_AddDebugLine(const float *start, const float *end, int forceDraw);
void __cdecl VP_DebugArrow(const float *pos, const float *angles);
void __cdecl G_InitVehiclePaths();
void __cdecl G_FreeVehiclePaths();
void __cdecl VP_ResetNode(vehicle_node_t *node);
void __cdecl G_SetupSplinePaths();
double __cdecl VP_CalcNodeSpeed(__int16 nodeIdx);
double __cdecl VP_CalcNodeLookAhead(__int16 nodeIdx);
void __cdecl VP_CalcNodeAngles(__int16 nodeIdx, float *angles);
void __cdecl G_ConnectVehiclePaths();
void __cdecl G_SetupVehiclePaths();
void __cdecl VP_ZeroNode(vehicle_node_t *node);
void __cdecl G_VehInitPathPos(vehicle_pathpos_t *vpp);
void __cdecl VP_InitNode(vehicle_node_t *node, __int16 nodeIdx);
void __cdecl G_VehFreePathPos(vehicle_pathpos_t *vpp);
void __cdecl G_VehSetUpPathPos(vehicle_pathpos_t *vpp, __int16 nodeIdx);
int __cdecl G_VehUpdatePathPos(vehicle_pathpos_t *vpp, __int16 testNode);
void __cdecl VP_GetAngles(const vehicle_pathpos_t *vpp, float *angles);
__int16 __cdecl VPP_GetCurrentNode(const vehicle_pathpos_t *vpp, __int16 currentNode);
void __cdecl VP_GetLookAheadXYZCustom(const vehicle_pathpos_t *vpp, float *lookXYZ);
void __cdecl VP_GetLookAheadXYZ(const vehicle_pathpos_t *vpp, float *lookXYZ);
int __cdecl VP_UpdatePathPosCustom(vehicle_pathpos_t *vpp, const float *dir, __int16 nodeTest);
double __cdecl VP_GetSpeed(const vehicle_pathpos_t *vpp);
double __cdecl VP_GetLookAhead(const vehicle_pathpos_t *vpp);
double __cdecl VP_GetSlide(const vehicle_pathpos_t *vpp);
int __cdecl VP_UpdatePathPos(vehicle_pathpos_t *vpp, const float *dir, __int16 nodeTest);
void __cdecl VP_BeginSwitchNode(const vehicle_pathpos_t *vpp);
void __cdecl VP_CopyNode(const vehicle_node_t *src, vehicle_node_t *dst);
void __cdecl VP_EndSwitchNode(const vehicle_pathpos_t *vpp);
void __cdecl G_VehSetSwitchNode(vehicle_pathpos_t *vpp, __int16 srcNodeIdx, __int16 dstNodeIdx);
vehicle_node_t *__cdecl G_FindVehicleNode(const SpawnVar *spawnVar);
void __cdecl VP_ParseFields(vehicle_node_t *node, const SpawnVar *spawnVar, bool setScriptVariable);
void __cdecl VP_ParseField(const char *key, char *value, vehicle_node_t *node, bool setScriptVariable);
void __cdecl VP_SetScriptVariable(const char *key, char *value, vehicle_node_t *node);
void __cdecl SP_info_vehicle_node(const SpawnVar *spawnVar, int rotated, int radiantLiveUpdate);
void __cdecl G_ClearSelectedVehicleNode();
void __cdecl G_ProcessVehicleNodeCommand(const RadiantCommand *command, SpawnVar *spawnVar);
unsigned __int16 __cdecl GScr_GetVehicleNodeIndex(unsigned int index);
void __cdecl GScr_AddFieldsForVehicleNode();
void __cdecl GScr_GetVehicleNodeField(unsigned int entnum, unsigned int offset);
void __cdecl GScr_GetVehicleNode();
void __cdecl G_SpawnHeliHeightLock(SpawnVar *spawnVar);
