#pragma once

void __cdecl FX_UnregisterAll();
unsigned __int8 *__cdecl FX_AllocMem(unsigned int size);
PhysPreset *__cdecl FX_RegisterPhysPreset(const char *name);
unsigned __int8 *__cdecl Hunk_AllocPhysPresetPrecache(int size);
XModel *__cdecl FX_RegisterModel(char *modelName);
bool __cdecl FX_RegisterMarkMaterials(const char *materialName, Material **materials);
Material *__cdecl FX_RegisterMaterial(char *material);
char __cdecl FX_ParseName(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseNonAtlasFlags(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseFlagsField(const char **parse, FxFlagOutputSet *flagOutputSet);
char __cdecl FX_ParseSingleFlag(const char *token, FxFlagOutputSet *flagOutputSet);
bool __cdecl FX_ParseSpawnRange(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseVector2(const char **parse, float *value);
char __cdecl FX_ParseFloat(const char **parse, float *value);
bool __cdecl FX_ParseFadeInRange(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseFadeOutRange(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseSpawnFrustumCullRadius(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseSpawnDefLooping(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseInt(const char **parse, int *value);
bool __cdecl FX_ParseSpawnDefOneShot(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseIntRange(const char **parse, FxIntRange *range);
bool __cdecl FX_ParseSpawnDelayMsec(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseLifeSpanMsec(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseSpawnOrgX(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseSpawnOrgY(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseSpawnOrgZ(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseSpawnOffsetRadius(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseSpawnOffsetHeight(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseSpawnAnglePitch(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseSpawnAngleYaw(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseSpawnAngleRoll(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseAngleVelPitch(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseAngleVelYaw(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseAngleVelRoll(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseInitialRot(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseGravity(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseElasticity(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseWindinfluence(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseAtlasBehavior(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseAtlasIndex(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseAtlasIndexRange(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseAtlasFps(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseAtlasLoopCount(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseAtlasColIndexBits(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseAtlasRowIndexBits(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseAtlasEntryCount(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseVelGraph0X(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseGraphRange(
        const char **parse,
        int dimCount,
        float minValue,
        float maxValue,
        float *scale,
        const FxCurve **shape);
char __cdecl FX_ParseCurve(const char **parse, int dimCount, float minValue, float maxValue, const FxCurve **shape);
bool __cdecl FX_ParseVelGraph0Y(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseVelGraph0Z(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseVelGraph1X(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseVelGraph1Y(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseVelGraph1Z(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseRotGraph(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseSizeGraph0(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseSizeGraph1(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseScaleGraph(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseColorGraph(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseAlphaGraph(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseCollOffset(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseVector(const char **parse, float *value);
char __cdecl FX_ParseLightingFrac(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseCollRadius(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseFxOnImpact(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseEffectRef(const char **parse, const FxEffectDef **fx);
char __cdecl FX_ParseFxOnDeath(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseSortOrder(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParsePriority(const char **parse);
char __cdecl FX_ParseAlphaFadeTimeMsec(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseMaxWindMagnitude(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseMaxWindLife(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseMaxWindInterval(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseEmission(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseEmitDist(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseEmitDistVariance(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseAttachment(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseTrailRepeatTime(const char **parse);
char __cdecl FX_ParseTrailSplitDist(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseTrailScrollTime(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseTrailRepeatDist(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseBillboardSprite(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_RegisterAsset_Material(char *name, FxElemVisuals *visuals);
char __cdecl FX_ParseOrientedSprite(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseRotatedSprite(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseCloud(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseTail(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseLine(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseTrail(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseTrailDef(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseDecal(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_RegisterAsset_DecalMaterials(const char *name, FxElemMarkVisuals *visuals);
char __cdecl FX_ParseModel(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_RegisterAsset_Model(char *name, FxElemVisuals *visuals);
char __cdecl FX_ParseLight(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_SetEditorElemType(FxEditorElemDef *edElemDef, unsigned __int8 type);
char __cdecl FX_ParseSpotLight(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseRunner(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_RegisterAsset_EffectDef(char *name, FxElemVisuals *visuals);
char __cdecl FX_ParseSound(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_RegisterAsset_SoundAliasName(char *name, FxElemVisuals *visuals);
char __cdecl FX_ParseElemSpawnSound(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseElemSpawnSoundAsset(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseBillboardTopWidth(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseBillboardBottomWidth(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseRotationAxis(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseVector4(const char **parse, float *value);
bool __cdecl FX_ParseCloudDensityRange(const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseEffectBoundingBoxDim(const char **parse, FxEditorEffectDef *edEffectDef);
bool __cdecl FX_ParseEffectBoundingBoxCentre(const char **parse, FxEditorEffectDef *edEffectDef);
char __cdecl FX_ParseEffectFlags(const char **parse, FxEditorEffectDef *edEffectDef);
char __cdecl FX_ParseEffectPriority(const char **parse, FxEditorEffectDef *edEffectDef);
bool __cdecl FX_ParseBillboardPivot(const char **parse, FxEditorElemDef *edElemDef);
char __cdecl FX_ParseEditorElem(int version, const char **parse, FxEditorElemDef *edElemDef);
bool __cdecl FX_ParseEditorElemField(const char **parse, FxEditorElemDef *edElemDef, const char *token);
char __cdecl FX_LoadEditorEffectFromBuffer(
        const char *buffer,
        const char *parseSessionName,
        FxEditorEffectDef *edEffectDef);
char __cdecl FX_ParseEditorEffect(const char **parse, FxEditorEffectDef *edEffectDef);
bool __cdecl FX_ParseEditorEffectField(const char **parse, FxEditorEffectDef *edEffectDef, const char *token);
bool __cdecl FX_LoadEditorEffect(const char *name, FxEditorEffectDef *edEffectDef);
const FxEffectDef *__cdecl FX_Load(const char *name);
const FxEffectDef *__cdecl FX_LoadFailed(const char *name);
const FxEffectDef *__cdecl FX_Register(char *name);
const FxEffectDef *__cdecl FX_Register_FastFile(const char *name);
const FxEffectDef *__cdecl FX_Register_LoadObj(char *name);
int __cdecl FX_GetHashIndex(char *name, bool *exists);
int __cdecl FX_HashName(char *name);
void __cdecl FX_RegisterDefaultEffect();
unsigned __int8 *__cdecl Hunk_AllocPhysPresetPrecache(unsigned int size);
