#pragma once

void __cdecl CL_SetStance(int localClientNum, StanceState stance);
void __cdecl IN_UpdateUseCount();
void __cdecl IN_UpdateUseHeld();
void __cdecl IN_CenterView();
bool __cdecl IN_IsTalkKeyHeld();
int __cdecl CL_MouseEvent(int x, int y, int dx, int dy);
void __cdecl CL_SetCursorPos(unsigned int x, unsigned int y);
void __cdecl CL_ShowSystemCursor(bool show);
bool __cdecl CL_KeyActiveOrPressed(int localClientNum, unsigned int kbButton);
void __cdecl CL_UpdateCmdButton(
        int localClientNum,
        bitarray<51> *cmdButton_bits,
        int kbButton,
        int buttonBit,
        int numBits);
void __cdecl CL_WritePacket(int localClientNum);
bool __cdecl CG_IsRemoteGuidingMissile(int localClientNum);
void __cdecl CL_SendCmd(int localClientNum);
bool __cdecl CL_ReadyToSendPacket(int localClientNum);
void __cdecl CL_CreateCmdsDuringConnection(int localClientNum);
void __cdecl CL_CreateNewCommands(int localClientNum);
usercmd_s *__cdecl CL_CreateCmd(usercmd_s *result, int localClientNum);
void __cdecl CL_AdjustAngles(int localClientNum);
double __cdecl CL_KeyState(kbutton_t *key);
void __cdecl CL_KeyMove(int localClientNum, usercmd_s *cmd);
void __cdecl CL_StanceButtonUpdate(int localClientNum);
bool __cdecl CG_IsSprinting(int localClientNum);
void __cdecl CL_AddCurrentStanceToCmd(int localClientNum, usercmd_s *cmd);
void __cdecl CL_DoubleTapButtonUpdate(int localClientNum, usercmd_s *cmd);
void __cdecl CL_GamepadMove(int localClientNum, usercmd_s *cmd);
void __cdecl CL_RandomMove(usercmd_s *cmd);
void __cdecl CL_MouseMove(int localClientNum, usercmd_s *cmd);
void __cdecl CL_GetMouseMovement(clientActive_t *cl, float *mx, float *my);
void __cdecl CL_CmdButtons(int localClientNum, usercmd_s *cmd);
void __cdecl CL_FinishMove(int localClientNum, usercmd_s *cmd);
char __cdecl CG_HandleLocationSelectionInput(int localClientNum, usercmd_s *cmd);
void __cdecl CL_Input(int localClientNum);
void __cdecl CL_InitInput();
void __cdecl IN_MLookDown();
void __cdecl IN_MLookUp();
void __cdecl IN_UpDown();
void __cdecl IN_KeyDown(kbutton_t *b);
void __cdecl IN_UpUp();
void __cdecl IN_KeyUp(kbutton_t *b);
void __cdecl IN_DownDown();
void __cdecl IN_DownUp();
void __cdecl IN_LeftDown();
void __cdecl IN_LeftUp();
void __cdecl IN_RightDown();
void __cdecl IN_RightUp();
void __cdecl IN_ForwardDown();
void __cdecl IN_ForwardUp();
void __cdecl IN_BackDown();
void __cdecl IN_BackUp();
void __cdecl IN_LookupDown();
void __cdecl IN_LookupUp();
void __cdecl IN_LookdownDown();
void __cdecl IN_LookdownUp();
void __cdecl IN_MoveleftDown();
void __cdecl IN_MoveleftUp();
void __cdecl IN_MoverightDown();
void __cdecl IN_MoverightUp();
void __cdecl IN_SpeedDown();
void __cdecl IN_LeaveADS();
void __cdecl IN_SpeedUp();
void __cdecl IN_StrafeDown();
void __cdecl IN_StrafeUp();
void __cdecl IN_Attack_Down();
void __cdecl IN_Attack_Up();
void __cdecl IN_Breath_Down();
void __cdecl IN_Breath_Up();
void __cdecl IN_MeleeBreath_Down();
void __cdecl IN_MeleeBreath_Up();
void __cdecl IN_Frag_Down();
void __cdecl IN_Frag_Up();
void __cdecl IN_Smoke_Down();
void __cdecl IN_Smoke_Up();
void __cdecl IN_Gas_Down();
void __cdecl IN_Gas_Up();
void __cdecl IN_Reverse_Down();
void __cdecl IN_Reverse_Up();
void __cdecl IN_Handbrake_Down();
void __cdecl IN_Handbrake_Up();
void __cdecl IN_SwitchSeat_Down();
void __cdecl IN_SwitchSeat_Up();
void __cdecl IN_VehicleBoost_Down();
void __cdecl IN_VehicleBoost_Up();
void __cdecl IN_VehicleAttack_Down();
void __cdecl IN_VehicleAttack_Up();
void __cdecl IN_VehicleAttackSecond_Down();
void __cdecl IN_VehicleAttackSecond_Up();
void __cdecl IN_VehicleMoveUp_Down();
void __cdecl IN_VehicleMoveUp_Up();
void __cdecl IN_VehicleMoveDown_Down();
void __cdecl IN_VehicleMoveDown_Up();
void __cdecl IN_VehicleSpecialAbility_Down();
void __cdecl IN_VehicleSpecialAbility_Up();
void __cdecl IN_VehicleFirePickup_Down();
void __cdecl IN_VehicleFirePickup_Up();
void __cdecl IN_VehicleSwapPickup_Down();
void __cdecl IN_VehicleSwapPickup_Up();
void __cdecl IN_VehicleDropDeployable_Down();
void __cdecl IN_VehicleDropDeployable_Up();
void __cdecl IN_BreathSprint_Down();
void __cdecl IN_BreathSprint_Up();
void __cdecl IN_Melee_Down();
void __cdecl IN_Melee_Up();
void __cdecl IN_Activate_Down();
void __cdecl IN_Activate_Up();
void __cdecl IN_Reload_Down();
void __cdecl IN_Reload_Up();
void __cdecl IN_UseReload_Down();
void __cdecl IN_UseReload_Up();
void __cdecl IN_LeanLeft_Down();
void __cdecl IN_LeanLeft_Up();
void __cdecl IN_LeanRight_Down();
void __cdecl IN_LeanRight_Up();
void __cdecl IN_Prone_Down();
void __cdecl IN_Prone_Up();
void __cdecl IN_Stance_Down();
void __cdecl IN_Stance_Up();
void __cdecl IN_ToggleADS();
void __cdecl IN_Throw_Down();
void __cdecl IN_Throw_Up();
void __cdecl IN_ToggleADS_Throw_Down();
void __cdecl IN_ToggleADS_Throw_Up();
void __cdecl IN_Speed_Throw_Down();
void __cdecl IN_Speed_Throw_Up();
void __cdecl IN_LowerStance();
void __cdecl IN_RaiseStance();
void __cdecl IN_ToggleCrouch();
void __cdecl CL_ToggleStance(int localClientNum, StanceState preferredStance);
void __cdecl IN_ToggleProne();
void __cdecl IN_GoProne();
void __cdecl IN_GoCrouch();
void __cdecl IN_GoStandDown();
void __cdecl IN_GoStandUp();
void __cdecl IN_SprintDown();
void __cdecl IN_SprintUp();
void __cdecl IN_SpecNext_Down();
void __cdecl IN_SpecNext_Up();
void __cdecl IN_SpecPrev_Down();
void __cdecl IN_SpecPrev_Up();
void __cdecl IN_ToggleSpec_Down();
void __cdecl IN_ToggleSpec_Up();
void __cdecl IN_ToggleView();
void __cdecl IN_TalkDown();
void __cdecl IN_TalkUp();
void __cdecl CL_ShutdownInput();
void __cdecl CL_ClearKeys(int localClientNum);
