#pragma once

void __cdecl Menus_FreeAllMemory(UiContext *dc);
void __cdecl Menu_FreeMemory(menuDef_t *menu);
void __cdecl Menu_FreeItemMemory(itemDef_s *item);
void __cdecl UI_MapLoadInfo(const char *filename);
void __cdecl UI_ParseMenuMaterial(const char *key, char *value);
void __cdecl PC_ResetConditionStack();
int __cdecl PC_CndStackPush(
        int handle,
        ExpressionStatement expressionStatement,
        bool fireOnTrue,
        bool incrementLevel,
        int blockID,
        int constructID,
        int type);
int __cdecl PC_CndStackModifyTop();
int __cdecl PC_CndStackPopLevel();
int __cdecl PC_CndStackAddConditionsToScript(GenericEventScript **baseScript, char *accumulatedScriptCommands);
int __cdecl MenuParse_name(menuDef_t *menu, int handle);
int __cdecl PC_String_Parse(int handle, const char **out);
int  MenuParse_fullscreen@<eax>(long double a1@<esi:edi>, menuDef_t *menu, int handle);
int  PC_Int_Parse@<eax>(long double a1@<esi:edi>, int handle, int *i);
void PC_SourceError(int handle, char *format, ...);
int  PC_Int_Expression_Parse@<eax>(long double a1@<esi:edi>, int handle, int *i);
int  MenuParse_rect@<eax>(long double a1@<esi:edi>, menuDef_t *menu, int handle);
int  PC_Rect_Parse@<eax>(long double a1@<esi:edi>, int handle, rectDef_s *r);
int  PC_Float_Parse@<eax>(long double a1@<esi:edi>, int handle, float *f);
int  PC_Float_Expression_Parse@<eax>(long double a1@<esi:edi>, int handle, float *f);
int __cdecl PC_Flag_ParseOptional(int handle, int *i);
int  PC_Byte_Parse@<eax>(long double a1@<esi:edi>, int handle, unsigned __int8 *b);
int __cdecl MenuParse_visible(menuDef_t *menu, int handle);
int __cdecl MenuParse_visiblityBits(menuDef_t *menu, int handle);
int __cdecl MenuParse_onFocus(menuDef_t *menu, int handle);
int __cdecl PC_EventScript_Parse(int handle, GenericEventScript **baseScript);
int __cdecl MenuParse_leaveFocus(menuDef_t *menu, int handle);
int __cdecl MenuParse_onOpen(menuDef_t *menu, int handle);
int __cdecl MenuParse_onClose(menuDef_t *menu, int handle);
int __cdecl MenuParse_onESC(menuDef_t *menu, int handle);
int __cdecl MenuParse_execExp(menuDef_t *menu, int handle);
int  MenuParse_border@<eax>(long double a1@<esi:edi>, menuDef_t *menu, int handle);
int  MenuParse_borderSize@<eax>(long double a1@<esi:edi>, menuDef_t *menu, int handle);
int  MenuParse_backcolor@<eax>(long double a1@<esi:edi>, menuDef_t *menu, int handle);
int  PC_Color_Parse@<eax>(long double a1@<esi:edi>, int handle, float (*c)[4]);
int  MenuParse_forecolor@<eax>(long double a1@<esi:edi>, menuDef_t *menu, int handle);
int  MenuParse_bordercolor@<eax>(long double a1@<esi:edi>, menuDef_t *menu, int handle);
int  MenuParse_focuscolor@<eax>(long double a1@<esi:edi>, menuDef_t *menu, int handle);
int  MenuParse_disablecolor@<eax>(long double a1@<esi:edi>, menuDef_t *menu, int handle);
int  MenuParse_outlinecolor@<eax>(long double a1@<esi:edi>, menuDef_t *menu, int handle);
int __cdecl MenuParse_background(menuDef_t *menu, int handle);
int  ItemParse_ownerdrawFlag@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
int  MenuParse_ownerdraw@<eax>(long double a1@<esi:edi>, menuDef_t *menu, int handle);
int __cdecl MenuParse_popup(menuDef_t *menu);
int __cdecl MenuParse_outOfBounds(menuDef_t *menu);
int __cdecl MenuParse_soundLoop(menuDef_t *menu, int handle);
int  MenuParse_fadeClamp@<eax>(long double a1@<esi:edi>, menuDef_t *menu, int handle);
int  MenuParse_fadeAmount@<eax>(long double a1@<esi:edi>, menuDef_t *menu, int handle);
int  MenuParse_fadeInAmount@<eax>(long double a1@<esi:edi>, menuDef_t *menu, int handle);
int  MenuParse_fadeCycle@<eax>(long double a1@<esi:edi>, menuDef_t *menu, int handle);
int __cdecl MenuParse_itemDef(menuDef_t *menu, int handle);
void __cdecl Item_Init(itemDef_s *item, int imageTrack);
void __cdecl Window_Init(windowDef_t *w);
int __cdecl Item_Parse(int handle, itemDef_s *item);
void __cdecl Item_PostParse(itemDef_s *item);
void __cdecl Item_InitControls(itemDef_s *item);
void __cdecl Item_ValidateTypeData(itemDef_s *item, int handle);
int __cdecl MenuParse_execKey(menuDef_t *menu, int handle);
int __cdecl PC_Char_Parse(int handle, char *out);
int  MenuParse_execKeyInt@<eax>(long double a1@<esi:edi>, menuDef_t *menu, int handle);
int  MenuParse_blurWorld@<eax>(long double a1@<esi:edi>, menuDef_t *menu, int handle);
int __cdecl MenuParse_legacySplitScreenScale(menuDef_t *menu, int handle);
int __cdecl SetItemStaticFlag(menuDef_t *menu, int handle, int flag);
int __cdecl MenuParse_hiddenDuringScope(menuDef_t *menu, int handle);
int __cdecl MenuParse_hiddenDuringFlashbang(menuDef_t *menu, int handle);
int __cdecl MenuParse_hiddenDuringUI(menuDef_t *menu, int handle);
int __cdecl MenuParse_allowedBinding(menuDef_t *menu, int handle);
int __cdecl MenuParse_allowSignIn(menuDef_t *menu, int handle);
int  MenuParse_ui3dWindowId@<eax>(long double a1@<esi:edi>, menuDef_t *menu, int handle);
int  MenuParse_priority@<eax>(long double a1@<esi:edi>, menuDef_t *menu, int handle);
int  MenuParse_openSlideSpeed@<eax>(long double a1@<esi:edi>, menuDef_t *menu, int handle);
int  MenuParse_closeSlideSpeed@<eax>(long double a1@<esi:edi>, menuDef_t *menu, int handle);
int  MenuParse_openSlideDirection@<eax>(long double a1@<esi:edi>, menuDef_t *menu, int handle);
int  MenuParse_closeSlideDirection@<eax>(long double a1@<esi:edi>, menuDef_t *menu, int handle);
int  MenuParse_openFadingTime@<eax>(long double a1@<esi:edi>, menuDef_t *menu, int handle);
int  MenuParse_closeFadingTime@<eax>(long double a1@<esi:edi>, menuDef_t *menu, int handle);
int  MenuParse_control@<eax>(long double a1@<esi:edi>, menuDef_t *menu, int handle);
int  ItemParse_frame@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
int  WindowParse_frame@<eax>(long double a1@<esi:edi>, windowDef_t *window, int handle);
void __cdecl Menu_SetupKeywordHash();
int __cdecl ItemParse_name(itemDef_s *item, int handle);
int __cdecl ItemParse_focusSound(itemDef_s *item, int handle);
int __cdecl ItemParse_text(itemDef_s *item, int handle);
int __cdecl ItemParse_textfile(itemDef_s *item, int handle);
char *__cdecl UI_FileText(char *fileName);
int __cdecl ItemParse_textsavegame(itemDef_s *item);
int __cdecl ItemParse_textcinematicsubtitle(itemDef_s *item);
int __cdecl ItemParse_group(itemDef_s *item, int handle);
int  ItemParse_rect@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
int  ItemParse_origin@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
int  ItemParse_style@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
int __cdecl ItemParse_decoration(itemDef_s *item);
int __cdecl ItemParse_notselectable(itemDef_s *item, int handle);
int __cdecl ItemParse_noScrollBars(itemDef_s *item, int handle);
int __cdecl ItemParse_noBlinkingHighlight(itemDef_s *item, int handle);
int __cdecl ItemParse_usePaging(itemDef_s *item, int handle);
int __cdecl ItemParse_autowrapped(itemDef_s *item);
int __cdecl ItemParse_horizontalscroll(itemDef_s *item);
int  ItemParse_type@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
bool  ItemParse_elementwidth@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
bool  ItemParse_elementheight@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
bool  ItemParse_special@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
int  ItemParse_elementtype@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
int  ItemParse_columns@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
int __cdecl PC_Int_ParseLine(int handle, int *i);
int  ItemParse_menuItemsDef@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
int  ItemParse_menuColDef@<eax>(
        long double a1@<esi:edi>,
        listBoxDef_s *listPtr,
        int handle,
        MenuCell *cells,
        int cellCount);
int  ItemParse_menuarea@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
int  ItemParse_userarea@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
bool  ItemParse_border@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
bool  ItemParse_bordersize@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
int __cdecl ItemParse_visible(itemDef_s *item, int handle);
int __cdecl ItemParse_visiblityBits(itemDef_s *item, int handle);
bool  ItemParse_ownerdraw@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
bool  ItemParse_align@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
int  ItemParse_textalign@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
bool __cdecl ItemParse_IsValidTextAlignment(unsigned int textAlignMode);
bool  ItemParse_textalignx@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
bool  ItemParse_textaligny@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
bool  ItemParse_textscale@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
bool  ItemParse_textstyle@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
bool  ItemParse_rotation@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
bool  ItemParse_textfont@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
int  ItemParse_backcolor@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
int  ItemParse_forecolor@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
int  ItemParse_bordercolor@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
int __cdecl ItemParse_modal(itemDef_s *item);
bool  ItemParse_outlinecolor@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
int __cdecl ItemParse_background(itemDef_s *item, int handle);
int __cdecl ItemParse_doubleClick(itemDef_s *item, int handle);
int __cdecl ItemParse_rightClick(itemDef_s *item, int handle);
int __cdecl ItemParse_onEnter(itemDef_s *item, int handle);
int __cdecl ItemParse_onFocus(itemDef_s *item, int handle);
int __cdecl ItemParse_leaveFocus(itemDef_s *item, int handle);
bool __cdecl ItemParse_mouseEnter(itemDef_s *item, int handle);
int __cdecl PC_Script_Parse(int handle, const char **out);
bool __cdecl ItemParse_mouseExit(itemDef_s *item, int handle);
bool __cdecl ItemParse_mouseEnterText(itemDef_s *item, int handle);
bool __cdecl ItemParse_mouseExitText(itemDef_s *item, int handle);
int __cdecl ItemParse_action(itemDef_s *item, int handle);
int __cdecl ItemParse_accept(itemDef_s *item, int handle);
bool __cdecl ItemParse_dvarTest(itemDef_s *item, int handle);
int __cdecl ItemParse_dvar(itemDef_s *item, int handle);
int  ItemParse_maxChars@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
int __cdecl Item_Parse_maxCharsGotoNext(itemDef_s *item, int handle);
int  ItemParse_maxPaintChars@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
bool  ItemParse_dvarFloat@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
int __cdecl ItemParse_dvarStrList(itemDef_s *item, int handle);
int  ItemParse_dvarFloatList@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
int __cdecl ItemParse_dvarEnumList(itemDef_s *item, int handle);
int __cdecl ItemParse_actionOnEnterPressOnly(itemDef_s *item, int handle);
int __cdecl ItemParse_enableDvar(itemDef_s *item, int handle);
int __cdecl ItemParse_disableDvar(itemDef_s *item, int handle);
int __cdecl ItemParse_showDvar(itemDef_s *item, int handle);
int __cdecl ItemParse_hideDvar(itemDef_s *item, int handle);
int __cdecl ItemParse_focusDvar(itemDef_s *item, int handle);
bool __cdecl ItemParse_onEvent(itemDef_s *item, int handle);
int __cdecl ItemParse_execKey(itemDef_s *item, int handle);
int  ItemParse_execKeyInt@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
int __cdecl ItemParse_execExp(itemDef_s *item, int handle);
int  ItemParse_gameMsgWindowIndex@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
int  ItemParse_gameMsgWindowMode@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
int  ItemParse_selectBorder@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
int  ItemParse_elementHighlightColor@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
int  ItemParse_elementBackgroundColor@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
int  ItemParse_disableColor@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
int  ItemParse_focusColor@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
int __cdecl ItemParse_selectIcon(itemDef_s *item, int handle);
int __cdecl ItemParse_backgroundItemListbox(itemDef_s *item, int handle);
int __cdecl ItemParse_highlightTexture(itemDef_s *item, int handle);
int __cdecl ItemParse_onListboxSelectionChange(itemDef_s *item, int handle);
int  ItemParse_ui3dWindowId@<eax>(long double a1@<esi:edi>, itemDef_s *item, int handle);
int __cdecl ItemParse_state(itemDef_s *item, int handle);
void __cdecl Item_SetupKeywordHash();
MenuList *__cdecl UI_LoadMenu(const char *menuFile, int imageTrack);
MenuList * UI_LoadMenu_LoadObj@<eax>(long double a1@<esi:edi>, char *menuFile, int imageTrack);
char  UI_ParseMenuInternal@<al>(long double a1@<esi:edi>, char *menuFile, int imageTrack);
int  Asset_Parse@<eax>(long double a1@<esi:edi>, int handle);
char __cdecl Menu_New(int handle, int imageTrack);
void __cdecl Menu_Init(menuDef_t *menu, int imageTrack);
int __cdecl Menu_Parse(int handle, menuDef_t *menu);
void __cdecl Menu_PostParse(menuDef_t *menu);
MenuList *__cdecl UI_LoadMenus(const char *menuFile, int imageTrack);
MenuList * UI_LoadMenus_LoadObj@<eax>(long double a1@<esi:edi>, char *menuFile, int imageTrack);
int  Load_Menu@<eax>(long double a1@<esi:edi>, const char **p, int imageTrack);
MenuList *__cdecl UI_LoadMenus_FastFile(const char *menuFile);
int __cdecl KeywordHash_KeySeed(const char *keyword, int hashCount, int seed);
