#pragma once

int __cdecl BG_EmblemsGetColorCount();
int __cdecl BG_EmblemsGetUnlockedLayerCount(int controllerIndex);
int __cdecl BG_EmblemsGetLayerCost(int layer);
int __cdecl BG_EmblemsGetLayerUnlockLevel(int layer);
int __cdecl BG_EmblemsGetPurchasedLayerCount(int controllerIndex);
char __cdecl BG_EmblemsPurchaseLayer(int controllerIndex);
void __cdecl BG_EmblemsFlushResults();
ResultCache *__cdecl BG_EmblemsGetResults(int controllerIndex, unsigned int include, unsigned int exclude);
int __cdecl ResultSort(__int16 *a, __int16 *b);
int __cdecl BG_EmblemsGetIconCount(int controllerIndex, unsigned int include, unsigned int exclude);
int __cdecl BG_EmblemsGetIconCount();
__int16 __cdecl BG_EmblemsGetIconID(int controllerIndex, int index, unsigned int include, unsigned int exclude);
int __cdecl BG_EmblemsGetPurchasedIconCount(int controllerIndex);
const char *__cdecl BG_EmblemsGetIconDesc(int controllerIndex, __int16 id);
const char *__cdecl BG_EmblemsGetIconUnlockDesc(int controllerIndex, __int16 id);
int __cdecl BG_EmblemsGetIconCost(__int16 id);
int __cdecl BG_EmblemsGetIconUnlockLevel(__int16 id);
int __cdecl BG_EmblemsGetIconUnlockPLevel(__int16 id);
int __cdecl BG_EmblemsGetIconUnclassifyAt(__int16 id);
int __cdecl BG_EmblemsGetIconDefaultColor(__int16 id);
GfxImage *__cdecl BG_EmblemsGetIconImage(__int16 id);
double __cdecl BG_EmblemsGetIconOutlineSize(__int16 id);
bool __cdecl BG_EmblemsIsIconLocked(int controllerIndex, __int16 id);
bool __cdecl BG_EmblemsIsIconClassified(int controllerIndex, __int16 id);
bool __cdecl BG_EmblemsIsIconPurchased(int controllerIndex, __int16 id);
char __cdecl BG_EmblemsPurchaseIcon(int controllerIndex, __int16 id);
int __cdecl BG_EmblemsGetCategoryCount();
const char *__cdecl BG_EmblemsGetCategoryDesc(int index);
int __cdecl BG_EmblemsGetBackgroundCount();
int __cdecl BG_EmblemsGetTotalBackgroundCount();
int __cdecl BG_EmblemsGetPurchasedBackgroundCount(int controllerIndex);
__int16 __cdecl BG_EmblemsGetBackgroundID(int index);
int __cdecl BG_EmblemsGetBackgroundIndex(__int16 id);
const char *__cdecl BG_EmblemsGetBackgroundDesc(int controllerIndex, __int16 id);
const char *__cdecl BG_EmblemsGetBackgroundUnlockDesc(int controllerIndex, __int16 id);
int __cdecl BG_EmblemsGetBackgroundCost(__int16 id);
int __cdecl BG_EmblemsGetBackgroundUnlockLevel(__int16 id);
int __cdecl BG_EmblemsGetBackgroundUnlockPLevel(__int16 id);
int __cdecl BG_EmblemsGetBackgroundUnclassifyAt(__int16 id);
Material *__cdecl BG_EmblemsGetBackgroundMaterial(__int16 id);
char __cdecl BG_EmblemsIsBackgroundLocked(int controllerIndex, __int16 id);
bool __cdecl BG_EmblemsIsBackgroundClassified(int controllerIndex, __int16 id);
bool __cdecl BG_EmblemsIsBackgroundPurchased(int controllerIndex, __int16 id);
char __cdecl BG_EmblemsPurchaseBackground(int controllerIndex, __int16 id);
void __cdecl BG_EmblemsWriteMsg(msg_t *msg, __int16 background, CompositeEmblemLayer *layers, int layerCount);
void __cdecl BG_EmblemsReadMsg(msg_t *msg, __int16 *background, CompositeEmblemLayer *layers, int layerCount);
char *__cdecl BG_EmblemsWriteString(__int16 background, CompositeEmblemLayer *layers, int layerCount);
bool __cdecl BG_EmblemsReadString(const char *str, __int16 *background, CompositeEmblemLayer *layers, int layerCount);
void __cdecl BG_EmblemsInit();
void __cdecl BG_EmblemsPurchaseLayer_f();
void __cdecl BG_EmblemsPurchaseIcon_f();
const char *__cdecl Cmd_Argv(int argIndex);
CmdArgs *__cdecl Cmd_Args();
void __cdecl BG_EmblemsPurchaseBackgroundByID_f();
void __cdecl BG_EmblemsPurchaseBackgroundByIndex_f();
void __cdecl BG_EmblemsClearDefaults();
void __cdecl BG_EmblemsSetDefaultForLevel(int minlevel, int maxlevel, CompositeEmblemLayer *s_emblem, int layerCount);
void __cdecl BG_EmblemsGenerateDefault(int controllerIndex, int level, CompositeEmblemLayer *layers, int layerCount);
unsigned int __cdecl SV_CACValidate_GetPurchasedEmblemLayers(unsigned __int8 *buffer);
bool __cdecl SV_CACValidate_IsBackgroundPurchased(unsigned __int8 *buffer, int rank, __int16 id);
bool __cdecl SV_CACValidate_IsBackgroundLockedForRank(unsigned __int8 *buffer, int rank, __int16 id);
bool __cdecl SV_CACValidate_IsIconPurchased(unsigned __int8 *buffer, int rank, __int16 id);
bool __cdecl SV_CACValidate_IsIconLockedForRank(unsigned __int8 *buffer, int rank, __int16 id);
