#pragma once

void __cdecl BG_LoadPenetrationDepthTable();
void __cdecl BG_ParsePenetrationDepthTable(const char *penetrateType, float *depthTable, char *buffer);
char __cdecl BG_AdvanceTrace(BulletFireParams *bp, BulletTraceResults *br, float dist);
double __cdecl BG_GetSurfacePenetrationDepth(const WeaponDef *weapDef, unsigned int surfaceType);
void __cdecl PM_StartWeaponAnim(playerState_s *ps, int anim, int leftAnim);
const char *__cdecl BG_GetImpactTypeName(int impactTypeIndex);
unsigned int __cdecl BG_GetViewmodelWeaponIndex(const playerState_s *ps);
int __cdecl BG_GetFirstAvailableOffhand(const playerState_s *ps, int offhandSlot);
int __cdecl BG_GetFirstEquippedOffhand(const playerState_s *ps, int offhandSlot);
int *__cdecl BG_GetWeaponState(playerState_s *ps, bool leftGun);
bool __cdecl BG_IsAimDownSightWeapon(unsigned int weaponIndex);
bool __cdecl BG_CanPlayerHaveWeapon(unsigned int weaponIndex);
bool __cdecl BG_ValidateWeaponNumber(unsigned int weaponIndex);
bool __cdecl BG_IsWeaponValid(const playerState_s *ps, unsigned int weaponIndex);
bool __cdecl BG_WeaponBlocksProne(unsigned int weapIndex);
bool __cdecl BG_IsOverheatingWeapon(unsigned int weapIndex);
bool __cdecl BG_IsBayonetWeapon(unsigned int weapIndex);
bool __cdecl BG_IsUseAsMeleeWeapon(unsigned int weapIndex);
int __cdecl BG_TakePlayerWeapon(playerState_s *ps, unsigned int weaponIndex);
void __cdecl BG_TakeHeldWeapon(playerState_s *ps, unsigned int weaponIndex);
void __cdecl BG_GetSpreadForWeapon(
        const playerState_s *ps,
        const WeaponDef *weapDef,
        float *minSpread,
        float *maxSpread);
void __cdecl PM_UpdateAimDownSightFlag(pmove_t *pm, pml_t *pml);
bool __cdecl PM_IsAdsAllowed(pmove_t *pm, pml_t *pml);
void __cdecl PM_ExitAimDownSight(playerState_s *ps);
void __cdecl PM_UpdateScopeZoom(pmove_t *pm);
void __cdecl PM_UpdateSpinLerp(pmove_t *pm, pml_t *pml);
void __cdecl PM_UpdateAimDownSightLerp(pmove_t *pm, pml_t *pml);
bool __cdecl BG_UsingVehicleWeapon(const playerState_s *ps);
bool __cdecl BG_ADSFullyUp(const playerState_s *ps);
bool __cdecl BG_UsingSniperScope(const playerState_s *ps);
int __cdecl PM_InteruptWeaponWithProneMove(playerState_s *ps);
bool __cdecl BG_PlayerWeaponOverheating(const playerState_s *ps, unsigned int weapon);
void __cdecl BG_PlayerWeaponOverheatUpdate(playerState_s *ps, unsigned int weapon, float amount);
PlayerHeldWeapon *__cdecl BG_GetHeldWeapon(playerState_s *ps, unsigned int weaponIndex);
bool __cdecl PM_IsWeaponMinFireTimeElapsed(playerState_s *ps, bool leftGun);
unsigned int __cdecl PM_GetWeaponIndexForHand(playerState_s *ps);
bool __cdecl BG_IsAltSwitch(playerState_s *ps, unsigned int lastWeapon, unsigned int weapon);
bool __cdecl BG_CanFastSwitch(const WeaponDef *weapDef, int weaponState);
char __cdecl BG_IsQuickSwitch(unsigned int oldweapon, unsigned int newweapon, int weaponState);
void __cdecl PM_AdjustAimSpreadScale(pmove_t *pm, pml_t *pml);
bool __cdecl ShotLimitReached(playerState_s *ps, const WeaponDef *weapDef);
unsigned int *__cdecl BG_GetWeaponShotCount(playerState_s *ps, bool leftGun);
int __cdecl PM_GetWeaponFireButton(unsigned int weapon);
void __cdecl PM_Weapon_Idle(playerState_s *ps);
void __cdecl PM_Weapon(pmove_t *pm, pml_t *pml);
void __cdecl PM_UpdateHoldBreath(pmove_t *pm, pml_t *pml);
void __cdecl PM_StartHoldBreath(playerState_s *ps);
void __cdecl PM_EndHoldBreath(playerState_s *ps);
int __cdecl PM_Weapon_CheckForRechamber(playerState_s *ps, int delayedAction);
bool __cdecl BG_PlayerWeaponNeedsRechambered(const playerState_s *ps, unsigned int weaponIndex);
void __cdecl BG_PlayerWeaponSetNeedsRechamber(playerState_s *ps, unsigned int weaponIndex, bool needsRechamber);
void __cdecl PM_Weapon_FinishRechamber(playerState_s *ps);
void __cdecl PM_ContinueWeaponAnim(playerState_s *ps, int anim, int leftAnim);
void __cdecl PM_Weapon_FinishWeaponChange(pmove_t *pm, int previousWeaponState);
bool __cdecl BG_PlayerEverHadWeapon(const playerState_s *ps, unsigned int weaponIndex);
void __cdecl BG_PlayerSetEverHadWeapon(playerState_s *ps, unsigned int weaponIndex, bool hadWeapon);
void __cdecl PM_Weapon_BeginWeaponRaise(
        playerState_s *ps,
        unsigned int anim,
        unsigned int time,
        float aim,
        int altSwitch);
void __cdecl BG_TakeClipOnlyWeaponIfEmpty(playerState_s *ps, unsigned int weaponIndex);
int __cdecl BG_GetAmmoNotInClip(const playerState_s *ps, unsigned int weaponIndex);
int __cdecl BG_GetAmmoNotInClipForAmmoIndex(const playerState_s *ps, int ammoIndex);
unsigned __int16 __cdecl BG_GetValidPrimaryWeaponForAltMode(
        const playerState_s *ps,
        unsigned int newWeapon,
        unsigned int lastWeaponAltModeSwitch);
void __cdecl PM_Weapon_FinishWeaponRaise(playerState_s *ps);
void __cdecl PM_Weapon_FinishReloadStart(pmove_t *pm, int delayedAction);
void __cdecl PM_SetReloadingState(playerState_s *ps);
bool __cdecl BG_PlayerWeaponQuickReload(const playerState_s *ps, unsigned int weaponIndex);
int *__cdecl BG_GetWeaponTime(playerState_s *ps, bool leftGun);
void __cdecl PM_SetWeaponReloadAddAmmoDelay(playerState_s *ps);
int *__cdecl BG_GetWeaponDelay(playerState_s *ps, bool leftGun);
int __cdecl PM_Weapon_AllowReload(playerState_s *ps);
int __cdecl BG_GetClipSize(unsigned int weaponIndex);
void __cdecl PM_Weapon_ReloadDelayedAction(playerState_s *ps);
void __cdecl BG_PlayerSetWeaponQuickReload(playerState_s *ps, unsigned int weaponIndex, bool quickReload);
void __cdecl PM_Weapon_FinishReload(pmove_t *pm, int delayedAction);
void __cdecl PM_Weapon_FinishReloadEnd(playerState_s *ps);
void __cdecl PM_Weapon_CheckFuelTime(pmove_t *pm, pml_t *pml);
void __cdecl PM_Weapon_CheckForReload(pmove_t *pm);
int __cdecl BG_PlayerFuelTankTime(const playerState_s *ps, unsigned int weaponIndex);
void __cdecl PM_BeginWeaponReload(pmove_t *pm);
bool __cdecl BG_PlayDWThirdPersonReload(playerState_s *ps);
bool __cdecl PM_CheckForReloadInterferingWeaponStates(pmove_t *pm, playerState_s *ps, int weaponState);
bool __cdecl BurstFirePending(playerState_s *ps);
void __cdecl UpdatePendingTriggerPull(pmove_t *pm);
void __cdecl CheckStackedFire(pmove_t *pm);
int __cdecl PM_Weapon_WeaponTimeAdjust(pmove_t *pm, pml_t *pml);
bool __cdecl WeaponUsesBurstCooldown(unsigned int weaponIdx);
void __cdecl PM_Weapon_CheckForChangeWeapon(pmove_t *pm);
void __cdecl PM_BeginWeaponChange(pmove_t *pm, unsigned int newweapon, bool quick);
int __cdecl PM_Weapon_ShouldBeFiring(pmove_t *pm, int delayedAction, bool testOnly);
void __cdecl PM_Weapon_FireWeapon(pmove_t *pm, int delayedAction);
void __cdecl PM_HoldBreathFire(playerState_s *ps);
void __cdecl BG_SwitchWeaponsIfEmpty(playerState_s *ps);
bool __cdecl BG_CheckIfDualWieldEmpty(playerState_s *ps);
void __cdecl PM_Weapon_StartFiring(pmove_t *pm, int delayedAction);
char __cdecl BG_CheckIfLastShot(playerState_s *ps, unsigned int weaponIndex);
int __cdecl PM_Weapon_CheckFiringAmmo(pmove_t *pm);
void __cdecl PM_Weapon_Jam(playerState_s *ps);
void __cdecl PM_Weapon_SetFPSFireAnim(playerState_s *ps);
void __cdecl PM_Weapon_AddFiringAimSpreadScale(playerState_s *ps);
char __cdecl PM_WeaponAllowPlant(pmove_t *pm);
void __cdecl Vec2NormalizeFast(float *v);
void __cdecl DrawPlantDebug(float *start, float *end);
bool __cdecl PM_Weapon_IsHoldingGrenade(pmove_t *pm);
void __cdecl PM_Weapon_MeleeEnd(playerState_s *ps);
const WeaponDef *__cdecl PM_Weapon_GetMeleeWeapDef(playerState_s *ps);
void __cdecl PM_Weapon_MeleeFire(playerState_s *ps);
void __cdecl PM_Weapon_CheckForMelee(pmove_t *pm, pml_t *pml, int delayedAction);
void __cdecl PM_Weapon_MeleeInit(pmove_t *pm);
void __cdecl PM_Weapon_OffHandPrepare(pmove_t *pm);
void __cdecl PM_Weapon_OffHandHold(playerState_s *ps);
void __cdecl PM_Weapon_OffHandStart(pmove_t *pm);
void __cdecl PM_Weapon_OffHand(pmove_t *pm);
void __cdecl PM_Weapon_OffHandEnd(playerState_s *ps);
void __cdecl PM_Weapon_CheckForOffHand(pmove_t *pm);
void __cdecl PM_Weapon_OffHandInit(playerState_s *ps);
void __cdecl PM_SendEmtpyOffhandEvent(playerState_s *ps, OffhandSlot offhandSlot);
char __cdecl PM_UpdateGrenadeThrow(playerState_s *ps, pml_t *pml);
char __cdecl PM_Weapon_CheckGrenadeHold(pmove_t *pm, int delayedAction);
void __cdecl PM_Weapon_CheckForDetonation(pmove_t *pm);
void __cdecl PM_Weapon_CheckForGrenadeThrowCancel(pmove_t *pm);
void __cdecl PM_Detonate(playerState_s *ps, int delayedAction);
void __cdecl PM_Weapon_CheckForNightVision(pmove_t *pm);
void __cdecl PM_Weapon_FinishNightVisionWear(playerState_s *ps);
void __cdecl PM_Weapon_FinishNightVisionRemove(playerState_s *ps);
void __cdecl PM_WeaponSwimIn(playerState_s *ps);
void __cdecl PM_WeaponSwimOut(playerState_s *ps);
void __cdecl Sprint_State_Loop(playerState_s *ps);
void __cdecl ContinuousFire_State_Loop(playerState_s *ps);
void __cdecl Dtp_State_Out(playerState_s *ps);
void __cdecl Dtp_State_Loop(playerState_s *ps);
void __cdecl PM_Weapon_CheckForSprint(pmove_t *pm);
void __cdecl Sprint_State_Raise(playerState_s *ps);
void __cdecl Sprint_State_Drop(playerState_s *ps);
void __cdecl PM_Weapon_CheckForContinuousFire(pmove_t *pm, int delayedAction);
void __cdecl ContinuousFire_State_In(playerState_s *ps);
void __cdecl ContinuousFire_State_Out(playerState_s *ps);
void __cdecl PM_Weapon_CheckForDtp(pmove_t *pm);
void __cdecl Dtp_State_In(playerState_s *ps);
void __cdecl PM_Weapon_CheckForSlide(pmove_t *pm);
void __cdecl Slide_State_In(playerState_s *ps);
void __cdecl PM_Weapon_CheckForDeploy(pmove_t *pm);
void __cdecl Deploy_State_Deploy(playerState_s *ps);
void __cdecl Deploy_State_Breakdown(playerState_s *ps);
void __cdecl PM_Weapon_CheckForMantle(pmove_t *pm);
int __cdecl BG_CheckForUniversalActionDW(playerState_s *ps);
void __cdecl PM_Weapon_Turret(pmove_t *pm);
void __cdecl PM_ResetWeaponState(playerState_s *ps);
void __cdecl BG_WeaponFireRecoil(const playerState_s *ps, float *recoilSpeed, float *kickAVel);
int __cdecl BG_PlayerWeaponCountPrimaryTypes(const playerState_s *ps);
bool __cdecl BG_PlayerWeaponsFull_Primaries(const playerState_s *ps);
char __cdecl BG_PlayerHasCompatibleWeapon(const playerState_s *ps, unsigned int weaponIndex);
bool __cdecl BG_ThrowingBackGrenade(const playerState_s *ps);
void __cdecl BG_CalcVehicleTurretWeaponPosOffset(float positionFrac, const WeaponDef *weapDef, float *outOffset);
WeaponVariantDef *__cdecl BG_LoadWeaponVariantDef(char *name);
WeaponVariantDef *__cdecl BG_LoadWeaponVariantDef_LoadObj(char *name);
WeaponVariantDef *__cdecl BG_LoadWeaponVariantDef_FastFile(const char *name);
void __cdecl BG_AssertOffhandIndexOrNone(unsigned int offHandIndex);
int __cdecl BG_GetFuelTankTime(const playerState_s *ps, unsigned int weaponIndex);
void __cdecl BG_SetFuelTankTime(playerState_s *ps, unsigned int weaponIndex, int time);
void __cdecl BG_AddFuelTankTime(playerState_s *ps, unsigned int weaponIndex, int time);
char __cdecl BG_HoldWeapon(playerState_s *ps, unsigned int weaponIndex);
int __cdecl BG_GetFreeHeldWeaponSlot(const playerState_s *ps);
const char *__cdecl BG_WeaponName(unsigned int weapon);
void __cdecl BG_StringCopy(unsigned __int8 *member, const char *keyValue);
