#pragma once

void __cdecl Load_byteArray(bool atStreamStart, int count);
void __cdecl Load_charArray(bool atStreamStart, int count);
void __cdecl Load_int(bool atStreamStart);
void __cdecl Load_intArray(bool atStreamStart, int count);
void __cdecl Load_unsignedArray(bool atStreamStart, int count);
void __cdecl Loadunsigned intArray(bool atStreamStart, int count);
void __cdecl Load_uint(bool atStreamStart);
void __cdecl Load_uintArray(bool atStreamStart, int count);
void __cdecl Load_float(bool atStreamStart);
void __cdecl Load_floatArray(bool atStreamStart, int count);
void __cdecl Load_raw_uintArray(bool atStreamStart, int count);
unsigned __int8 *__cdecl AllocLoad_raw_uint128();
void __cdecl Load_raw_uint128Array(bool atStreamStart, int count);
void __cdecl Load_raw_byteArray(bool atStreamStart, int count);
void __cdecl Load_raw_byte16Array(bool atStreamStart, int count);
void __cdecl Load_vec2_tArray(bool atStreamStart, int count);
void __cdecl Load_vec3_t(bool atStreamStart);
void __cdecl Load_vec3_tArray(bool atStreamStart, int count);
void __cdecl Load_vec4_tArray(bool atStreamStart, int count);
void __cdecl Load_DObjAnimMatArray(bool atStreamStart, int count);
void __cdecl Load_shared_vec3_t(bool atStreamStart);
void __cdecl Load_shared_vec3_tArray(bool atStreamStart, int count);
void __cdecl Load_shortArray(bool atStreamStart, int count);
void __cdecl Load_ushortArray(bool atStreamStart, int count);
void __cdecl Load_XQuat2(bool atStreamStart);
void __cdecl Load_XQuat2Array(bool atStreamStart, int count);
unsigned __int8 *__cdecl AllocLoad_XBlendInfo();
void __cdecl Load_UnsignedShortArray(bool atStreamStart, int count);
void __cdecl Load_ScriptString(bool atStreamStart);
void __cdecl Load_ScriptStringArray(bool atStreamStart, int count);
ComBurnableSample *__cdecl AllocLoad_raw_byte();
void __cdecl Load_ConstCharArray(bool atStreamStart, int count);
void __cdecl Load_TempString(bool atStreamStart);
void __cdecl Load_TempStringArray(bool atStreamStart, int count);
void __cdecl Load_XString(bool atStreamStart);
void __cdecl Load_XStringArray(bool atStreamStart, int count);
void __cdecl Load_ScriptStringList(bool atStreamStart);
void __cdecl Load_complex_tArray(bool atStreamStart, int count);
void __cdecl Load_dmaterial_tArray(bool atStreamStart, int count);
void __cdecl Mark_ScriptString();
void __cdecl Mark_ScriptStringArray(int count);
void __cdecl Load_XAnimIndices();
void __cdecl Load_XAnimDynamicIndicesDeltaQuat(bool atStreamStart);
void __cdecl Load_XAnimDeltaPartQuatDataFrames(bool atStreamStart);
void __cdecl Load_XAnimDeltaPartQuatData(bool atStreamStart);
void __cdecl Load_XAnimDeltaPartQuat(bool atStreamStart);
void __cdecl Load_XAnimDeltaPart(bool atStreamStart);
void __cdecl Load_XAnimDynamicIndicesTrans(bool atStreamStart);
void __cdecl Load_ByteVecArray(bool atStreamStart, int count);
void __cdecl Load_UShortVecArray(bool atStreamStart, int count);
void __cdecl Load_XAnimDynamicFrames();
void __cdecl Load_XAnimPartTransFrames(bool atStreamStart);
void __cdecl Load_XAnimPartTransData(bool atStreamStart);
void __cdecl Load_XAnimPartTrans(bool atStreamStart);
void __cdecl Load_XAnimNotifyInfo(bool atStreamStart);
void __cdecl Load_XAnimNotifyInfoArray(bool atStreamStart, int count);
void __cdecl Load_XAnimParts(bool atStreamStart);
void __cdecl Load_XAnimPartsPtr(bool atStreamStart);
void __cdecl Mark_XAnimNotifyInfo();
void __cdecl Mark_XAnimNotifyInfoArray(int count);
void __cdecl Mark_XAnimParts();
void __cdecl Mark_XAnimPartsPtr();
void __cdecl Load_XBoneInfoArray(bool atStreamStart, int count);
void __cdecl Load_snd_curveArray(bool atStreamStart, int count);
void __cdecl Load_snd_groupArray(bool atStreamStart, int count);
void __cdecl Load_snd_radverbArray(bool atStreamStart, int count);
void __cdecl Load_snd_masterArray(bool atStreamStart, int count);
void __cdecl Load_snd_panArray(bool atStreamStart, int count);
void __cdecl Load_snd_snapshot_groupArray(bool atStreamStart, int count);
void __cdecl Load_snd_snapshotArray(bool atStreamStart, int count);
void __cdecl Load_snd_contextArray(bool atStreamStart, int count);
void __cdecl Load_SndDriverGlobals(bool atStreamStart);
void __cdecl Load_SndDriverGlobalsPtr(bool atStreamStart);
void __cdecl Load_PackIndexEntryArray(bool atStreamStart, int count);
void __cdecl Load_PackIndex(bool atStreamStart);
void __cdecl Load_PackIndexPtr(bool atStreamStart);
void __cdecl Mark_SndDriverGlobalsPtr();
void __cdecl Mark_PackIndexPtr();
char *__cdecl AllocLoad_snd_align_char();
void __cdecl Load_snd_align_charArray(bool atStreamStart, int count);
void __cdecl Load_snd_asset(bool atStreamStart);
void __cdecl Load_LoadedSound(bool atStreamStart);
void __cdecl Load_char_align_2048Array(bool atStreamStart, int count);
void __cdecl Load_PrimedSound(bool atStreamStart);
void __cdecl Load_PrimedSoundPtr(bool atStreamStart);
void __cdecl Load_StreamedSound(bool atStreamStart);
void __cdecl Load_SoundFileRef();
void __cdecl Load_SoundFile(bool atStreamStart);
void __cdecl Load_SoundFileArray(bool atStreamStart, int count);
void __cdecl Load_snd_alias_t(bool atStreamStart);
void __cdecl Load_snd_alias_tArray(bool atStreamStart, int count);
void __cdecl Load_snd_alias_list_t(bool atStreamStart);
void __cdecl Load_snd_alias_list_tArray(bool atStreamStart, int count);
void __cdecl Load_SndIndexEntryArray(bool atStreamStart, int count);
void __cdecl Load_SndBank(bool atStreamStart);
void __cdecl Load_SndBankPtr(bool atStreamStart);
void __cdecl Load_SndPatch(bool atStreamStart);
void __cdecl Load_SndPatchPtr(bool atStreamStart);
void __cdecl Mark_SndBankPtr();
void __cdecl Mark_SndPatchPtr();
void __cdecl Load_MaterialInfo(bool atStreamStart);
void __cdecl Load_GfxWorldVertex0Array(bool atStreamStart, int count);
void __cdecl Load_GfxPackedVertex0Array(bool atStreamStart, int count);
void __cdecl Load_GfxBrushModelArray(bool atStreamStart, int count);
void __cdecl Load_XSurfaceCollisionLeafArray(bool atStreamStart, int count);
void __cdecl Load_XSurfaceCollisionNodeArray(bool atStreamStart, int count);
void __cdecl Load_XSurfaceCollisionTree(bool atStreamStart);
void __cdecl Load_XRigidVertList(bool atStreamStart);
void __cdecl Load_XRigidVertListArray(bool atStreamStart, int count);
void __cdecl Load_GfxVertexBuffer(bool atStreamStart);
void __cdecl Load_XBlendInfoArray(bool atStreamStart, int count);
void __cdecl Load_XSurfaceVertexInfo(bool atStreamStart);
void __cdecl Load_r_index_tArray(bool atStreamStart, int count);
void __cdecl Load_r_index16_tArray(bool atStreamStart, int count);
void __cdecl Load_XSurface(bool atStreamStart);
void __cdecl Load_XSurfaceArray(bool atStreamStart, int count);
void __cdecl Load_GfxTextureLoad(bool atStreamStart);
void __cdecl Load_GfxRawTextureArray(bool atStreamStart, int count);
void __cdecl Load_GfxImageLoadDef(bool atStreamStart);
void __cdecl Load_GfxImage(bool atStreamStart);
void __cdecl Load_GfxImagePtr(bool atStreamStart);
void __cdecl Load_GfxImagePtrArray(bool atStreamStart, int count);
void __cdecl Mark_GfxImagePtr();
void __cdecl Mark_GfxImagePtrArray(int count);
void __cdecl Load_water_t(bool atStreamStart);
void __cdecl Mark_water_t();
void __cdecl Load_GfxVertexShaderLoadDef(bool atStreamStart);
void __cdecl Load_GfxPixelShaderLoadDef(bool atStreamStart);
void __cdecl Load_MaterialVertexShaderProgram(bool atStreamStart);
void __cdecl Load_MaterialPixelShaderProgram(bool atStreamStart);
void __cdecl Load_MaterialVertexShader(bool atStreamStart);
void __cdecl Load_MaterialVertexShaderPtr(bool atStreamStart);
void __cdecl Load_MaterialPixelShader(bool atStreamStart);
void __cdecl Load_MaterialPixelShaderPtr(bool atStreamStart);
void __cdecl Load_MaterialVertexDeclaration(bool atStreamStart);
void __cdecl Load_MaterialArgumentCodeConst(bool atStreamStart);
void __cdecl Load_MaterialArgumentDef(bool atStreamStart);
void __cdecl Load_MaterialShaderArgument(bool atStreamStart);
void __cdecl Load_MaterialShaderArgumentArray(bool atStreamStart, int count);
void __cdecl Load_GfxStateBitsArray(bool atStreamStart, int count);
void __cdecl Load_MaterialPass(bool atStreamStart);
void __cdecl Load_MaterialPassArray(bool atStreamStart, int count);
void __cdecl Load_MaterialTechnique(bool atStreamStart);
void __cdecl Load_MaterialTextureDefInfo(bool atStreamStart);
void __cdecl Load_MaterialTextureDef(bool atStreamStart);
void __cdecl Load_MaterialTextureDefArray(bool atStreamStart, int count);
void __cdecl Load_MaterialConstantDefArray(bool atStreamStart, int count);
void __cdecl Load_MaterialTechniquePtr(bool atStreamStart);
void __cdecl Load_MaterialTechniquePtrArray(bool atStreamStart, int count);
void __cdecl Load_MaterialTechniqueSet(bool atStreamStart);
void __cdecl Load_MaterialTechniqueSetPtr(bool atStreamStart);
void __cdecl Load_Material(bool atStreamStart);
void __cdecl Load_MaterialHandle(bool atStreamStart);
void __cdecl Load_MaterialHandleArray(bool atStreamStart, int count);
void __cdecl Mark_MaterialTextureDefInfo();
void __cdecl Mark_MaterialTextureDef();
void __cdecl Mark_MaterialTextureDefArray(int count);
void __cdecl Mark_MaterialTechniqueSetPtr();
void __cdecl Mark_Material();
void __cdecl Mark_MaterialHandle();
void __cdecl Mark_MaterialHandleArray(int count);
void __cdecl Load_GfxLightImage(bool atStreamStart);
void __cdecl Load_GfxLightDef(bool atStreamStart);
void __cdecl Load_GfxLightDefPtr(bool atStreamStart);
void __cdecl Load_GfxLight(bool atStreamStart);
void __cdecl Mark_GfxLightImage();
void __cdecl Mark_GfxLightDef();
void __cdecl Mark_GfxLightDefPtr();
void __cdecl Mark_GfxLight();
void __cdecl Load_GfxSurface(bool atStreamStart);
void __cdecl Load_GfxSurfaceArray(bool atStreamStart, int count);
void __cdecl Load_GfxLightmapArray(bool atStreamStart);
void __cdecl Load_GfxLightmapArrayArray(bool atStreamStart, int count);
void __cdecl Mark_GfxSurface();
void __cdecl Mark_GfxSurfaceArray(int count);
void __cdecl Mark_GfxLightmapArray();
void __cdecl Mark_GfxLightmapArrayArray(int count);
void __cdecl Load_PhysPreset(bool atStreamStart);
void __cdecl Load_PhysPresetPtr(bool atStreamStart);
void __cdecl Mark_PhysPresetPtr();
void __cdecl Load_PhysConstraint(bool atStreamStart);
void __cdecl Load_PhysConstraintArray(bool atStreamStart, int count);
void __cdecl Load_PhysConstraints(bool atStreamStart);
void __cdecl Load_PhysConstraintsPtr(bool atStreamStart);
void __cdecl Mark_PhysConstraint();
void __cdecl Mark_PhysConstraintArray(int count);
void __cdecl Mark_PhysConstraints();
void __cdecl Mark_PhysConstraintsPtr();
void __cdecl Load_cplane_t(bool atStreamStart);
void __cdecl Load_cplane_tArray(bool atStreamStart, int count);
void __cdecl Load_cbrushside_t(bool atStreamStart);
void __cdecl Load_cbrushside_tArray(bool atStreamStart, int count);
void __cdecl Load_XModelCollTriArray(bool atStreamStart, int count);
void __cdecl Load_XModelCollSurf(bool atStreamStart);
void __cdecl Load_XModelCollSurfArray(bool atStreamStart, int count);
void __cdecl Load_XModelHighMipBoundsArray(bool atStreamStart, int count);
void __cdecl Load_XModelStreamInfo(bool atStreamStart);
void __cdecl Load_BrushWrapper(bool atStreamStart);
void __cdecl Load_PhysGeomInfo(bool atStreamStart);
void __cdecl Load_PhysGeomInfoArray(bool atStreamStart, int count);
void __cdecl Load_PhysGeomList(bool atStreamStart);
void __cdecl Load_Collmap(bool atStreamStart);
void __cdecl Load_CollmapArray(bool atStreamStart, int count);
void __cdecl Load_XModel(bool atStreamStart);
void __cdecl Load_XModelPtr(bool atStreamStart);
void __cdecl Load_XModelPtrArray(bool atStreamStart, int count);
void __cdecl Load_XModelPiece(bool atStreamStart);
void __cdecl Load_XModelPieceArray(bool atStreamStart, int count);
void __cdecl Load_XModelPieces(bool atStreamStart);
void __cdecl Load_XModelPiecesPtr(bool atStreamStart);
void __cdecl Mark_XModel();
void __cdecl Mark_XModelPtr();
void __cdecl Mark_XModelPtrArray(int count);
void __cdecl Mark_XModelPiece();
void __cdecl Mark_XModelPieceArray(int count);
void __cdecl Mark_XModelPieces();
void __cdecl Mark_XModelPiecesPtr();
void __cdecl Load_pathlink_tArray(bool atStreamStart, int count);
void __cdecl Load_pathnode_constant_t(bool atStreamStart);
void __cdecl Load_pathnode_t(bool atStreamStart);
void __cdecl Load_pathnode_tArray(bool atStreamStart, int count);
void __cdecl Load_pathbasenode_tArray(bool atStreamStart, int count);
void __cdecl Load_pathnode_tree_nodes_t(bool atStreamStart);
void __cdecl Load_pathnode_tree_ptr(bool atStreamStart);
void __cdecl Load_pathnode_tree_ptrArray(bool atStreamStart, int count);
void __cdecl Load_pathnode_tree_info_t(bool atStreamStart);
void __cdecl Load_pathnode_tree_t(bool atStreamStart);
void __cdecl Load_pathnode_tree_tArray(bool atStreamStart, int count);
void __cdecl Mark_pathnode_constant_t();
void __cdecl Mark_pathnode_t();
void __cdecl Mark_pathnode_tArray(int count);
void __cdecl Load_PathData(bool atStreamStart);
void __cdecl Load_GameWorldSp(bool atStreamStart);
void __cdecl Load_GameWorldMp(bool atStreamStart);
void __cdecl Load_GameWorldSpPtr(bool atStreamStart);
void __cdecl Load_GameWorldMpPtr(bool atStreamStart);
void __cdecl Mark_PathData();
void __cdecl Mark_GameWorldSp();
void __cdecl Mark_GameWorldMp();
void __cdecl Mark_GameWorldSpPtr();
void __cdecl Mark_GameWorldMpPtr();
void __cdecl Load_FxEffectDefHandle(bool atStreamStart);
void __cdecl Load_FxEffectDefHandleArray(bool atStreamStart, int count);
void __cdecl Load_FxEffectDefRef(bool atStreamStart);
void __cdecl Load_FxElemMarkVisuals(bool atStreamStart);
void __cdecl Load_FxElemMarkVisualsArray(bool atStreamStart, int count);
void __cdecl Load_FxElemVisuals(bool atStreamStart);
void __cdecl Load_FxElemVisualsArray(bool atStreamStart, int count);
void __cdecl Load_FxElemSpawnSound(bool atStreamStart);
void __cdecl Load_FxElemVisStateSampleArray(bool atStreamStart, int count);
void __cdecl Load_FxElemVelStateSampleArray(bool atStreamStart, int count);
void __cdecl Load_FxElemDefVisuals(bool atStreamStart);
void __cdecl Load_FxTrailVertexArray(bool atStreamStart, int count);
void __cdecl Load_FxTrailDef(bool atStreamStart);
void __cdecl Load_FxElemDef(bool atStreamStart);
void __cdecl Load_FxElemDefArray(bool atStreamStart, int count);
void __cdecl Load_FxEffectDef(bool atStreamStart);
void __cdecl Mark_FxEffectDefHandle();
void __cdecl Mark_FxEffectDefHandleArray(int count);
void __cdecl Mark_FxElemMarkVisuals();
void __cdecl Mark_FxElemMarkVisualsArray(int count);
void __cdecl Mark_FxElemVisuals();
void __cdecl Mark_FxElemVisualsArray(int count);
void __cdecl Mark_FxElemDefVisuals();
void __cdecl Mark_FxElemDef();
void __cdecl Mark_FxElemDefArray(int count);
void __cdecl Mark_FxEffectDef();
void __cdecl Load_DynEntityDef(bool atStreamStart);
void __cdecl Load_DynEntityDefArray(bool atStreamStart, int count);
void __cdecl Load_DynEntityPoseArray(bool atStreamStart, int count);
void __cdecl Load_DynEntityCollArray(bool atStreamStart, int count);
void __cdecl Load_DynEntityClientArray(bool atStreamStart, int count);
void __cdecl Load_DynEntityServerArray(bool atStreamStart, int count);
void __cdecl Mark_DynEntityDef();
void __cdecl Mark_DynEntityDefArray(int count);
void __cdecl Load_MapEnts(bool atStreamStart);
void __cdecl Load_MapEntsPtr(bool atStreamStart);
void __cdecl Mark_MapEntsPtr();
void __cdecl Load_cStaticModel_t(bool atStreamStart);
void __cdecl Load_cStaticModel_tArray(bool atStreamStart, int count);
void __cdecl Load_cNode_t(bool atStreamStart);
void __cdecl Load_cNode_tArray(bool atStreamStart, int count);
void __cdecl Load_cLeaf_tArray(bool atStreamStart, int count);
void __cdecl Load_cLeafBrushNodeLeaf_t(bool atStreamStart);
void __cdecl Load_cLeafBrushNodeChildren_t(bool atStreamStart);
void __cdecl Load_cLeafBrushNodeData_t(bool atStreamStart);
void __cdecl Load_cLeafBrushNode_t(bool atStreamStart);
void __cdecl Load_cLeafBrushNode_tArray(bool atStreamStart, int count);
void __cdecl Load_CollisionBorder(bool atStreamStart);
void __cdecl Load_CollisionBorderArray(bool atStreamStart, int count);
void __cdecl Load_CollisionPartition(bool atStreamStart);
void __cdecl Load_CollisionPartitionArray(bool atStreamStart, int count);
cbrush_t *__cdecl AllocLoad_GfxPackedVertex0();
void __cdecl Load_CollisionAabbTreeArray(bool atStreamStart, int count);
void __cdecl Load_cmodel_tArray(bool atStreamStart, int count);
void __cdecl Load_cbrush_t(bool atStreamStart);
void __cdecl Load_cbrush_tArray(bool atStreamStart, int count);
void __cdecl Load_LeafBrushArray(bool atStreamStart, int count);
void __cdecl Load_rope_tArray(bool atStreamStart, int count);
void __cdecl Load_clipMap_t(bool atStreamStart);
void __cdecl Load_clipMap_ptr(bool atStreamStart);
void __cdecl Mark_cStaticModel_t();
void __cdecl Mark_cStaticModel_tArray(int count);
void __cdecl Mark_clipMap_t();
void __cdecl Mark_clipMap_ptr();
void __cdecl Load_ComPrimaryLight(bool atStreamStart);
void __cdecl Load_ComPrimaryLightArray(bool atStreamStart, int count);
void __cdecl Load_ComWaterCellArray(bool atStreamStart, int count);
void __cdecl Load_ComBurnableSampleArray(bool atStreamStart, int count);
void __cdecl Load_ComBurnableCell(bool atStreamStart);
void __cdecl Load_ComBurnableCellArray(bool atStreamStart, int count);
void __cdecl Load_ComWorld(bool atStreamStart);
void __cdecl Load_ComWorldPtr(bool atStreamStart);
void __cdecl Mark_ComWorldPtr();
void __cdecl Load_operandInternalDataUnion(bool atStreamStart);
void __cdecl Load_Operand(bool atStreamStart);
void __cdecl Load_expressionRpnDataUnion(bool atStreamStart);
void __cdecl Load_expressionRpn(bool atStreamStart);
void __cdecl Load_expressionRpnArray(bool atStreamStart, int count);
void __cdecl Load_ExpressionStatement(bool atStreamStart);
void __cdecl Load_ScriptCondition(bool atStreamStart);
void __cdecl Load_ScriptConditionNext(bool atStreamStart);
void __cdecl Load_GenericEventScript(bool atStreamStart);
void __cdecl Load_GenericEventScriptNext(bool atStreamStart);
void __cdecl Load_GenericEventHandler(bool atStreamStart);
void __cdecl Load_GenericEventHandlerNext(bool atStreamStart);
void __cdecl Load_ItemKeyHandler(bool atStreamStart);
void __cdecl Load_ItemKeyHandlerNext(bool atStreamStart);
void __cdecl Load_editFieldDef_t(bool atStreamStart);
void __cdecl Load_editFieldDef_ptr(bool atStreamStart);
void __cdecl Load_multiDef_t(bool atStreamStart);
void __cdecl Load_multiDef_ptr(bool atStreamStart);
void __cdecl Load_enumDvarDef_t(bool atStreamStart);
void __cdecl Load_enumDvarDef_ptr(bool atStreamStart);
void __cdecl Load_MenuCell(bool atStreamStart);
void __cdecl Load_MenuCellArray(bool atStreamStart, int count);
void __cdecl Load_MenuRow(bool atStreamStart);
void __cdecl Load_MenuRowArray(bool atStreamStart, int count);
void __cdecl Load_animParamsDef_t(bool atStreamStart);
void __cdecl Load_windowDef_t(bool atStreamStart);
void __cdecl Load_Window(bool atStreamStart);
void __cdecl Load_animParamsDef_ptr(bool atStreamStart);
void __cdecl Load_animParamsDef_ptrArray(bool atStreamStart, int count);
void __cdecl Load_imageDef_t(bool atStreamStart);
void __cdecl Load_imageDef_ptr(bool atStreamStart);
void __cdecl Load_ownerDrawDef_t(bool atStreamStart);
void __cdecl Load_ownerDrawDef_ptr(bool atStreamStart);
void __cdecl Load_listBoxDef_t(bool atStreamStart);
void __cdecl Load_listBoxDef_ptr(bool atStreamStart);
void __cdecl Load_focusDefData_t(bool atStreamStart);
void __cdecl Load_focusItemDef_t(bool atStreamStart);
void __cdecl Load_focusItemDef_ptr(bool atStreamStart);
void __cdecl Load_gameMsgDef_t(bool atStreamStart);
void __cdecl Load_gameMsgDef_ptr(bool atStreamStart);
void __cdecl Load_textDefData_t(bool atStreamStart);
void __cdecl Load_textExp_t(bool atStreamStart);
void __cdecl Load_textDef_t(bool atStreamStart);
void __cdecl Load_textDef_ptr(bool atStreamStart);
void __cdecl Load_rectData_t(bool atStreamStart);
void __cdecl Load_itemDefData_t(bool atStreamStart);
void __cdecl Load_UIAnimInfo(bool atStreamStart);
void __cdecl Load_itemDef_t(bool atStreamStart);
menuDef_t *__cdecl AllocLoad_itemDef_t();
void __cdecl Load_itemDef_ptr(bool atStreamStart);
void __cdecl Load_itemDef_ptrArray(bool atStreamStart, int count);
void __cdecl Load_menuDef_t(bool atStreamStart);
void __cdecl Load_menuDef_ptr(bool atStreamStart);
void __cdecl Load_menuDef_ptrArray(bool atStreamStart, int count);
void __cdecl Load_MenuList(bool atStreamStart);
void __cdecl Load_MenuListPtr(bool atStreamStart);
void __cdecl Mark_windowDef_t();
void __cdecl Mark_Window();
void __cdecl Mark_listBoxDef_t();
void __cdecl Mark_listBoxDef_ptr();
void __cdecl Mark_focusDefData_t();
void __cdecl Mark_focusItemDef_t();
void __cdecl Mark_focusItemDef_ptr();
void __cdecl Mark_textDefData_t();
void __cdecl Mark_textDef_t();
void __cdecl Mark_textDef_ptr();
void __cdecl Mark_itemDefData_t();
void __cdecl Mark_itemDef_t();
void __cdecl Mark_itemDef_ptr();
void __cdecl Mark_itemDef_ptrArray(int count);
void __cdecl Mark_menuDef_t();
void __cdecl Mark_menuDef_ptr();
void __cdecl Mark_menuDef_ptrArray(int count);
void __cdecl Mark_MenuList();
void __cdecl Mark_MenuListPtr();
void __cdecl Load_LocalizeEntry(bool atStreamStart);
void __cdecl Load_LocalizeEntryPtr(bool atStreamStart);
void __cdecl Mark_LocalizeEntryPtr();
void __cdecl Load_FxImpactEntry(bool atStreamStart);
void __cdecl Load_FxImpactEntryArray(bool atStreamStart, int count);
void __cdecl Load_FxImpactTable(bool atStreamStart);
void __cdecl Load_FxImpactTablePtr(bool atStreamStart);
void __cdecl Mark_FxImpactEntry();
void __cdecl Mark_FxImpactEntryArray(int count);
void __cdecl Mark_FxImpactTable();
void __cdecl Mark_FxImpactTablePtr();
void __cdecl Load_DestructibleStage(bool atStreamStart);
void __cdecl Load_DestructibleStageArray(bool atStreamStart, int count);
void __cdecl Load_DestructiblePiece(bool atStreamStart);
void __cdecl Load_DestructiblePieceArray(bool atStreamStart, int count);
void __cdecl Load_DestructibleDef(bool atStreamStart);
void __cdecl Load_DestructibleDefPtr(bool atStreamStart);
void __cdecl Mark_DestructibleStage();
void __cdecl Mark_DestructibleStageArray(int count);
void __cdecl Mark_DestructiblePiece();
void __cdecl Mark_DestructiblePieceArray(int count);
void __cdecl Mark_DestructibleDef();
void __cdecl Mark_DestructibleDefPtr();
void __cdecl Load_flameTable(bool atStreamStart);
XAsset *__cdecl AllocLoad_FxElemVisStateSample();
void __cdecl Load_WeaponDef(bool atStreamStart);
void __cdecl Load_WeaponVariantDef(bool atStreamStart);
void __cdecl Load_WeaponVariantDefPtr(bool atStreamStart);
void __cdecl Mark_flameTable();
void __cdecl Mark_WeaponDef();
void __cdecl Mark_WeaponVariantDef();
void __cdecl Mark_WeaponVariantDefPtr();
void __cdecl Load_EmblemIcon(bool atStreamStart);
void __cdecl Load_EmblemIconArray(bool atStreamStart, int count);
void __cdecl Load_EmblemBackground(bool atStreamStart);
void __cdecl Load_EmblemBackgroundArray(bool atStreamStart, int count);
void __cdecl Load_EmblemLayerArray(bool atStreamStart, int count);
void __cdecl Load_EmblemCategory(bool atStreamStart);
void __cdecl Load_EmblemCategoryArray(bool atStreamStart, int count);
void __cdecl Load_EmblemSet(bool atStreamStart);
void __cdecl Load_EmblemSetPtr(bool atStreamStart);
void __cdecl Mark_EmblemIcon();
void __cdecl Mark_EmblemIconArray(int count);
void __cdecl Mark_EmblemBackground();
void __cdecl Mark_EmblemBackgroundArray(int count);
void __cdecl Mark_EmblemSet();
void __cdecl Mark_EmblemSetPtr();
void __cdecl Load_RawFile(bool atStreamStart);
void __cdecl Load_RawFilePtr(bool atStreamStart);
void __cdecl Mark_RawFilePtr();
void __cdecl Load_XGlobals(bool atStreamStart);
void __cdecl Load_XGlobalsPtr(bool atStreamStart);
void __cdecl Mark_XGlobalsPtr();
void __cdecl Load_StringTableCell(bool atStreamStart);
void __cdecl Load_StringTableCellArray(bool atStreamStart, int count);
void __cdecl Load_StringTable(bool atStreamStart);
void __cdecl Load_StringTablePtr(bool atStreamStart);
void __cdecl Mark_StringTablePtr();
void __cdecl Load_ddlMemberDef_t(bool atStreamStart);
void __cdecl Load_ddlMemberDef_tArray(bool atStreamStart, int count);
void __cdecl Load_ddlStructDef_t(bool atStreamStart);
void __cdecl Load_ddlStructDef_tArray(bool atStreamStart, int count);
void __cdecl Load_ddlEnumDef_t(bool atStreamStart);
void __cdecl Load_ddlEnumDef_tArray(bool atStreamStart, int count);
void __cdecl Load_ddlDef_t(bool atStreamStart);
void __cdecl Load_ddlDefNext(bool atStreamStart);
void __cdecl Load_ddlRoot_t(bool atStreamStart);
void __cdecl Load_ddlRoot_ptr(bool atStreamStart);
void __cdecl Mark_ddlRoot_ptr();
void __cdecl Load_GfxStaticModelDrawInst(bool atStreamStart);
void __cdecl Load_GfxStaticModelDrawInstArray(bool atStreamStart, int count);
void __cdecl Load_GfxStaticModelInstArray(bool atStreamStart, int count);
void __cdecl Mark_GfxStaticModelDrawInst();
void __cdecl Mark_GfxStaticModelDrawInstArray(int count);
void __cdecl Load_sunflare_t(bool atStreamStart);
void __cdecl Mark_sunflare_t();
void __cdecl Load_GfxReflectionProbeVolumeDataArray(bool atStreamStart, int count);
void __cdecl Load_GfxReflectionProbe(bool atStreamStart);
void __cdecl Load_GfxReflectionProbeArray(bool atStreamStart, int count);
void __cdecl Mark_GfxReflectionProbe();
void __cdecl Mark_GfxReflectionProbeArray(int count);
void __cdecl Load_OccluderArray(bool atStreamStart, int count);
void __cdecl Load_StaticModelIndexArray(bool atStreamStart, int count);
void __cdecl Load_GfxAabbTree(bool atStreamStart);
void __cdecl Load_GfxAabbTreeArray(bool atStreamStart, int count);
void __cdecl Load_GfxCell(bool atStreamStart);
void __cdecl Load_GfxCellArray(bool atStreamStart, int count);
void __cdecl Load_GfxPortal(bool atStreamStart);
void __cdecl Load_GfxPortalArray(bool atStreamStart, int count);
void __cdecl Load_GfxCullGroupArray(bool atStreamStart, int count);
void __cdecl Load_GfxLightGridEntryArray(bool atStreamStart, int count);
void __cdecl Load_GfxCompressedLightGridColorsArray(bool atStreamStart, int count);
void __cdecl Load_MaterialMemory(bool atStreamStart);
void __cdecl Load_MaterialMemoryArray(bool atStreamStart, int count);
void __cdecl Load_GfxWorldVertexData(bool atStreamStart);
void __cdecl Load_GfxWorldVertexLayerData(bool atStreamStart);
void __cdecl Load_aligned_byte_pointerArray(bool atStreamStart, int count);
void __cdecl Load_GfxLightGrid(bool atStreamStart);
void __cdecl Load_GfxStreamingAabbTreeArray(bool atStreamStart, int count);
void __cdecl Load_GfxWorldStreamInfo(bool atStreamStart);
void __cdecl Load_GfxSceneDynModelArray(bool atStreamStart, int count);
void __cdecl Load_GfxSceneDynBrushArray(bool atStreamStart, int count);
void __cdecl Load_GfxDrawSurfArray(bool atStreamStart, int count);
void __cdecl Load_GfxShadowGeometry(bool atStreamStart);
void __cdecl Load_GfxShadowGeometryArray(bool atStreamStart, int count);
void __cdecl Load_GfxWaterBuffer(bool atStreamStart);
void __cdecl Load_GfxWaterBufferArray(bool atStreamStart, int count);
void __cdecl Load_GfxWorldLodChainArray(bool atStreamStart, int count);
void __cdecl Load_GfxWorldLodInfoArray(bool atStreamStart, int count);
void __cdecl Load_GfxLightCoronaArray(bool atStreamStart, int count);
void __cdecl Load_GfxShadowMapVolumeArray(bool atStreamStart, int count);
void __cdecl Load_GfxExposureVolumeArray(bool atStreamStart, int count);
void __cdecl Load_GfxVolumePlaneArray(bool atStreamStart, int count);
void __cdecl Load_GfxLightRegionAxisArray(bool atStreamStart, int count);
void __cdecl Load_GfxLightRegionHull(bool atStreamStart);
void __cdecl Load_GfxLightRegionHullArray(bool atStreamStart, int count);
void __cdecl Load_GfxLightRegion(bool atStreamStart);
void __cdecl Load_GfxLightRegionArray(bool atStreamStart, int count);
void __cdecl Load_GfxWorldDpvsDynamic(bool atStreamStart);
void __cdecl Load_GfxWorldDpvsStatic(bool atStreamStart);
void __cdecl Load_GfxWorldDpvsPlanes(bool atStreamStart);
void __cdecl Load_GfxOutdoorBoundsArray(bool atStreamStart, int count);
void __cdecl Load_GfxHeroLightArray(bool atStreamStart, int count);
void __cdecl Load_GfxHeroLightTreeArray(bool atStreamStart, int count);
void __cdecl Load_GfxWorldDraw(bool atStreamStart);
void __cdecl Load_GfxWorld(bool atStreamStart);
void __cdecl Load_GfxWorldPtr(bool atStreamStart);
void __cdecl Mark_MaterialMemory();
void __cdecl Mark_MaterialMemoryArray(int count);
void __cdecl Mark_GfxWorldDpvsStatic();
void __cdecl Mark_GfxWorldDraw();
void __cdecl Mark_GfxWorld();
void __cdecl Mark_GfxWorldPtr();
void __cdecl Load_GlyphArray(bool atStreamStart, int count);
void __cdecl Load_Font(bool atStreamStart);
void __cdecl Load_FontHandle(bool atStreamStart);
void __cdecl Mark_Font();
void __cdecl Mark_FontHandle();
void __cdecl Load_GlassDef(bool atStreamStart);
void __cdecl Load_Glass(bool atStreamStart);
void __cdecl Load_GlassArray(bool atStreamStart, int count);
void __cdecl Load_Glasses(bool atStreamStart);
void __cdecl Load_GlassesPtr(bool atStreamStart);
void __cdecl Mark_GlassDef();
void __cdecl Mark_Glass();
void __cdecl Mark_GlassArray(int count);
void __cdecl Mark_Glasses();
void __cdecl Mark_GlassesPtr();
void __cdecl Load_XAssetHeader(bool atStreamStart);
void __cdecl Load_XAsset(bool atStreamStart);
void __cdecl Mark_XAssetHeader();
void __cdecl Mark_XAsset();
