#pragma once

void __cdecl Com_InitParse();
void __cdecl Com_InitParseInfo(parseInfo_t *pi);
void __cdecl Com_BeginParseSession(const char *filename);
ParseThreadInfo *__cdecl Com_GetParseThreadInfo();
void __cdecl Com_EndParseSession();
void __cdecl Com_ResetParseSessions();
void __cdecl Com_SetSpaceDelimited(int spaceDelimited);
void __cdecl Com_SetKeepStringQuotes(int keepStringQuotes);
void __cdecl Com_SetCSV(int csv);
void __cdecl Com_SetParseNegativeNumbers(int negativeNumbers);
int __cdecl Com_GetCurrentParseLine();
void __cdecl Com_SetScriptErrorPrefix(const char *prefix);
const char *__cdecl Com_GetScriptErrorPrefix();
void __cdecl Com_SetScriptWarningPrefix(const char *prefix);
const char *__cdecl Com_GetScriptWarningPrefix();
void Com_ScriptErrorDrop(char *msg, ...);
void Com_ScriptError(char *msg, ...);
void Com_ScriptWarning(char *msg, ...);
void __cdecl Com_UngetToken();
void __cdecl Com_ParseSetMark(const char **text, com_parse_mark_t *mark);
void __cdecl Com_ParseReturnToMark(const char **text, com_parse_mark_t *mark);
int __cdecl Com_Compress(char *data_p);
const char *__cdecl Com_GetLastTokenPos();
parseInfo_t *__cdecl Com_Parse(const char **data_p);
parseInfo_t *__cdecl Com_ParseExt(const char **data_p, int allowLineBreaks);
const char *__cdecl SkipWhitespace(const char *data, int *newLines);
parseInfo_t *__cdecl Com_ParseCSV(const char **data_p, int allowLineBreaks);
parseInfo_t *__cdecl Com_ParseOnLine(const char **data_p);
ParseTokenType __cdecl Com_GetTokenType();
int __cdecl Com_MatchToken(const char **buf_p, const char *match, int warning);
int __cdecl Com_SkipBracedSection(const char **program, unsigned int startDepth, int iMaxNesting);
void __cdecl Com_SkipRestOfLine(const char **data);
int __cdecl Com_GetArgCountOnLine(const char **data_p);
char *__cdecl Com_ParseRestOfLine(const char **data_p);
double __cdecl Com_ParseFloat(const char **buf_p);
double __cdecl Com_ParseFloatOnLine(const char **buf_p);
int __cdecl Com_ParseInt(const char **buf_p);
void __cdecl Com_Parse1DMatrix(const char **buf_p, int x, float *m);
