#pragma once

#include <universal/dvar.h>
#include <universal/mem_userhunk.h>

void __cdecl SV_SetConfigstring(int index, char *val);
void __cdecl SV_GetConfigstring(unsigned int index, char *buffer, int bufferSize);
unsigned int __cdecl SV_GetConfigstringConst(unsigned int index);
void __cdecl SV_SetConfigValueForKey(int start, int max, char *key, char *value);
void __cdecl SV_SetUserinfo(int index, char *val);
void __cdecl SV_GetUserinfo(int index, char *buffer, int bufferSize);
void __cdecl SV_CreateBaseline();
void __cdecl SV_SetXUIDConfigStrings();
void __cdecl SV_Startup(int controllerIndex);
void __cdecl SV_SetExpectedHunkUsage(char *mapname);
void __cdecl SV_ClearServer();
void __cdecl SV_InitArchivedSnapshot();
void __cdecl SV_SetSystemInfoConfig();
void __cdecl SV_SaveSystemInfo();
void __cdecl SV_SetServerDvarsBeforeScriptsInit();
void __cdecl    SV_SpawnServer(int controllerIndex, char *server, int mapIsPreloaded, int savegame);
char *__cdecl SV_AllocateClientMemory_SizeRequired(int maxLocalClients, int maxClients);
void __cdecl SV_AllocateClientMemory(HunkUser *hunk, int maxLocalClients, int maxClients);
void __cdecl SV_FreeClientMemory(HunkUser *hunk);
bool __cdecl SV_Loaded();
void __cdecl SV_Init();
void __cdecl SV_DropAllClients();
void __cdecl SV_Shutdown(const char *finalmsg);
void __cdecl SV_FinalMessage(const char *message);
void __cdecl SV_ClearServerThreadOwnsGame();
void __cdecl SV_IncServerThreadOwnsGame();
void __cdecl SV_DecServerThreadOwnsGame();
int __cdecl SV_GetServerThreadOwnsGame();
void __cdecl SV_CheckThread();


extern const dvar_t *sv_gametype;
extern const dvar_t *sv_privateClients;
extern const dvar_t *sv_hostname;
extern const dvar_t *sv_noname;
extern const dvar_t *sv_geolocation;
extern const dvar_t *sv_maxgrouperrors;
extern const dvar_t *sv_ownerid;
extern const dvar_t *sv_numreservedslots;
extern const dvar_t *sv_clientSideBullets;
extern const dvar_t *sv_clientSideVehicles;
extern const dvar_t *sv_penetrationCount;
extern const dvar_t *sv_axis_penetrationCount;
extern const dvar_t *sv_allies_penetrationCount;
extern const dvar_t *sv_bullet_range;
extern const dvar_t *sv_hitFXFrustumCutoff;
extern const dvar_t *sv_punkbuster;
extern const dvar_t *sv_security;
extern const dvar_t *sv_ranked;
extern const dvar_t *ui_ranked;
extern const dvar_t *sv_dedicatedmaxclients;
extern const dvar_t *sv_maxclients;
extern const dvar_t *sv_maxRate;
extern const dvar_t *sv_minPing;
extern const dvar_t *sv_maxPing;
extern const dvar_t *sv_timeout;
extern const dvar_t *sv_connectTimeout;
extern const dvar_t *sv_floodProtect;
extern const dvar_t *sv_showCommands;
extern const dvar_t *sv_writeConfigStrings;
extern const dvar_t *scr_writeConfigStrings;
extern const dvar_t *sv_dwlsgerror;
extern const dvar_t *sv_allowAnonymous;
extern const dvar_t *sv_disableClientConsole;
extern const dvar_t *sv_privatePassword;
extern const dvar_t *sv_allowDownload;
extern const dvar_t *sv_iwds;
extern const dvar_t *sv_iwdNames;
extern const dvar_t *sv_referencedIwds;
extern const dvar_t *sv_referencedIwdNames;
extern const dvar_t *sv_FFCheckSums;
extern const dvar_t *sv_FFNames;
extern const dvar_t *sv_referencedFFCheckSums;
extern const dvar_t *sv_referencedFFNames;
extern const dvar_t *sv_authenticating;
extern const dvar_t *sv_voice;
extern const dvar_t *sv_voiceQuality;
extern const dvar_t *sv_cheats;
extern const dvar_t *sv_pure;
extern const dvar_t *rcon_password;
extern const dvar_t *sv_fps;
extern const dvar_t *sv_showPingSpam;
extern const dvar_t *sv_zombietime;
extern const dvar_t *sv_reconnectlimit;
extern const dvar_t *sv_padPackets;
extern const dvar_t *sv_allowedClan1;
extern const dvar_t *sv_allowedClan2;
extern const dvar_t *sv_packet_info;
extern const dvar_t *sv_showAverageBPS;
extern const dvar_t *sv_kickBanTime;
extern const dvar_t *sv_debugMessageKey;
extern const dvar_t *sv_debugPacketContents;
extern const dvar_t *sv_debugPacketContentsForClientThisFrame;
extern const dvar_t *sv_showHuffmanData;
extern const dvar_t *sv_debugConstantConfigStrings;
extern const dvar_t *sv_loadMyChanges;
extern const dvar_t *sv_debugPlayerstate;
extern const dvar_t *sv_debugPacketContentsQuick;
extern const dvar_t *sv_printMessageSize;
extern const dvar_t *sv_mapRotation;
extern const dvar_t *sv_mapRotationCurrent;
extern const dvar_t *sv_debugRate;
extern const dvar_t *sv_debugReliableCmds;
extern const dvar_t *nextmap;
extern const dvar_t *com_movieIsPlaying;
extern const dvar_t *sv_wwwDownload;
extern const dvar_t *sv_wwwBaseURL;
extern const dvar_t *sv_wwwDlDisconnected;
extern const dvar_t *sv_smp;
extern const dvar_t *sv_network_fps;
extern const dvar_t *sv_assistWorkers;
extern const dvar_t *sv_clientArchive;